/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.crowd.funding.database.model.CategoryRegistration;
import com.crowd.funding.database.model.CategoryRegistrationModel;
import com.crowd.funding.database.model.CategoryRegistrationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CategoryRegistration service. Represents a row in the &quot;cf_category_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CategoryRegistrationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CategoryRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CategoryRegistrationImpl
 * @see CategoryRegistration
 * @see CategoryRegistrationModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CategoryRegistrationModelImpl extends BaseModelImpl<CategoryRegistration>
	implements CategoryRegistrationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a category registration model instance should use the {@link CategoryRegistration} interface instead.
	 */
	public static final String TABLE_NAME = "cf_category_details";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "CATEGORY_ID", Types.BIGINT },
			{ "CATEGORY_NAME", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CATEGORY_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CATEGORY_NAME", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table cf_category_details (uuid_ VARCHAR(75) null,CATEGORY_ID LONG not null primary key,CATEGORY_NAME VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table cf_category_details";
	public static final String ORDER_BY_JPQL = " ORDER BY categoryRegistration.CATEGORY_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY cf_category_details.CATEGORY_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.crowd.funding.database.model.CategoryRegistration"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.crowd.funding.database.model.CategoryRegistration"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.crowd.funding.database.model.CategoryRegistration"),
			true);
	public static final long UUID_COLUMN_BITMASK = 1L;
	public static final long CATEGORY_ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CategoryRegistration toModel(
		CategoryRegistrationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CategoryRegistration model = new CategoryRegistrationImpl();

		model.setUuid(soapModel.getUuid());
		model.setCATEGORY_ID(soapModel.getCATEGORY_ID());
		model.setCATEGORY_NAME(soapModel.getCATEGORY_NAME());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CategoryRegistration> toModels(
		CategoryRegistrationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CategoryRegistration> models = new ArrayList<CategoryRegistration>(soapModels.length);

		for (CategoryRegistrationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.crowd.funding.database.service.util.ServiceProps.get(
				"lock.expiration.time.com.crowd.funding.database.model.CategoryRegistration"));

	public CategoryRegistrationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CATEGORY_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCATEGORY_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CATEGORY_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CategoryRegistration.class;
	}

	@Override
	public String getModelClassName() {
		return CategoryRegistration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("CATEGORY_ID", getCATEGORY_ID());
		attributes.put("CATEGORY_NAME", getCATEGORY_NAME());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long CATEGORY_ID = (Long)attributes.get("CATEGORY_ID");

		if (CATEGORY_ID != null) {
			setCATEGORY_ID(CATEGORY_ID);
		}

		String CATEGORY_NAME = (String)attributes.get("CATEGORY_NAME");

		if (CATEGORY_NAME != null) {
			setCATEGORY_NAME(CATEGORY_NAME);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCATEGORY_ID() {
		return _CATEGORY_ID;
	}

	@Override
	public void setCATEGORY_ID(long CATEGORY_ID) {
		_CATEGORY_ID = CATEGORY_ID;
	}

	@JSON
	@Override
	public String getCATEGORY_NAME() {
		if (_CATEGORY_NAME == null) {
			return "";
		}
		else {
			return _CATEGORY_NAME;
		}
	}

	@Override
	public void setCATEGORY_NAME(String CATEGORY_NAME) {
		_CATEGORY_NAME = CATEGORY_NAME;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CategoryRegistration.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CategoryRegistration toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CategoryRegistration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CategoryRegistrationImpl categoryRegistrationImpl = new CategoryRegistrationImpl();

		categoryRegistrationImpl.setUuid(getUuid());
		categoryRegistrationImpl.setCATEGORY_ID(getCATEGORY_ID());
		categoryRegistrationImpl.setCATEGORY_NAME(getCATEGORY_NAME());

		categoryRegistrationImpl.resetOriginalValues();

		return categoryRegistrationImpl;
	}

	@Override
	public int compareTo(CategoryRegistration categoryRegistration) {
		long primaryKey = categoryRegistration.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CategoryRegistration)) {
			return false;
		}

		CategoryRegistration categoryRegistration = (CategoryRegistration)obj;

		long primaryKey = categoryRegistration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CategoryRegistrationModelImpl categoryRegistrationModelImpl = this;

		categoryRegistrationModelImpl._originalUuid = categoryRegistrationModelImpl._uuid;

		categoryRegistrationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CategoryRegistration> toCacheModel() {
		CategoryRegistrationCacheModel categoryRegistrationCacheModel = new CategoryRegistrationCacheModel();

		categoryRegistrationCacheModel.uuid = getUuid();

		String uuid = categoryRegistrationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			categoryRegistrationCacheModel.uuid = null;
		}

		categoryRegistrationCacheModel.CATEGORY_ID = getCATEGORY_ID();

		categoryRegistrationCacheModel.CATEGORY_NAME = getCATEGORY_NAME();

		String CATEGORY_NAME = categoryRegistrationCacheModel.CATEGORY_NAME;

		if ((CATEGORY_NAME != null) && (CATEGORY_NAME.length() == 0)) {
			categoryRegistrationCacheModel.CATEGORY_NAME = null;
		}

		return categoryRegistrationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", CATEGORY_ID=");
		sb.append(getCATEGORY_ID());
		sb.append(", CATEGORY_NAME=");
		sb.append(getCATEGORY_NAME());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.crowd.funding.database.model.CategoryRegistration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CATEGORY_ID</column-name><column-value><![CDATA[");
		sb.append(getCATEGORY_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CATEGORY_NAME</column-name><column-value><![CDATA[");
		sb.append(getCATEGORY_NAME());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CategoryRegistration.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CategoryRegistration.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _CATEGORY_ID;
	private String _CATEGORY_NAME;
	private long _columnBitmask;
	private CategoryRegistration _escapedModel;
}