/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.crowd.funding.database.model.CommentRegistration;
import com.crowd.funding.database.model.CommentRegistrationModel;
import com.crowd.funding.database.model.CommentRegistrationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CommentRegistration service. Represents a row in the &quot;cf_project_comment_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CommentRegistrationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommentRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommentRegistrationImpl
 * @see CommentRegistration
 * @see CommentRegistrationModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CommentRegistrationModelImpl extends BaseModelImpl<CommentRegistration>
	implements CommentRegistrationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a comment registration model instance should use the {@link CommentRegistration} interface instead.
	 */
	public static final String TABLE_NAME = "cf_project_comment_details";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "PROJECT_COMMENT_ID", Types.BIGINT },
			{ "PROJECT_ID", Types.BIGINT },
			{ "COMMENT", Types.VARCHAR },
			{ "ANSWER", Types.VARCHAR },
			{ "DONOR_USER_ID", Types.BIGINT },
			{ "COMMENT_DATE", Types.TIMESTAMP },
			{ "STATUS", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PROJECT_COMMENT_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("PROJECT_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("COMMENT", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ANSWER", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DONOR_USER_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("COMMENT_DATE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("STATUS", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table cf_project_comment_details (uuid_ VARCHAR(75) null,PROJECT_COMMENT_ID LONG not null primary key,PROJECT_ID LONG,COMMENT TEXT null,ANSWER TEXT null,DONOR_USER_ID LONG,COMMENT_DATE DATE null,STATUS INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table cf_project_comment_details";
	public static final String ORDER_BY_JPQL = " ORDER BY commentRegistration.PROJECT_COMMENT_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY cf_project_comment_details.PROJECT_COMMENT_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.crowd.funding.database.model.CommentRegistration"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.crowd.funding.database.model.CommentRegistration"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.crowd.funding.database.model.CommentRegistration"),
			true);
	public static final long PROJECT_COMMENT_ID_COLUMN_BITMASK = 1L;
	public static final long PROJECT_ID_COLUMN_BITMASK = 2L;
	public static final long STATUS_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CommentRegistration toModel(CommentRegistrationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CommentRegistration model = new CommentRegistrationImpl();

		model.setUuid(soapModel.getUuid());
		model.setPROJECT_COMMENT_ID(soapModel.getPROJECT_COMMENT_ID());
		model.setPROJECT_ID(soapModel.getPROJECT_ID());
		model.setCOMMENT(soapModel.getCOMMENT());
		model.setANSWER(soapModel.getANSWER());
		model.setDONOR_USER_ID(soapModel.getDONOR_USER_ID());
		model.setCOMMENT_DATE(soapModel.getCOMMENT_DATE());
		model.setSTATUS(soapModel.getSTATUS());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CommentRegistration> toModels(
		CommentRegistrationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CommentRegistration> models = new ArrayList<CommentRegistration>(soapModels.length);

		for (CommentRegistrationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.crowd.funding.database.service.util.ServiceProps.get(
				"lock.expiration.time.com.crowd.funding.database.model.CommentRegistration"));

	public CommentRegistrationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PROJECT_COMMENT_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPROJECT_COMMENT_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PROJECT_COMMENT_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommentRegistration.class;
	}

	@Override
	public String getModelClassName() {
		return CommentRegistration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("PROJECT_COMMENT_ID", getPROJECT_COMMENT_ID());
		attributes.put("PROJECT_ID", getPROJECT_ID());
		attributes.put("COMMENT", getCOMMENT());
		attributes.put("ANSWER", getANSWER());
		attributes.put("DONOR_USER_ID", getDONOR_USER_ID());
		attributes.put("COMMENT_DATE", getCOMMENT_DATE());
		attributes.put("STATUS", getSTATUS());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long PROJECT_COMMENT_ID = (Long)attributes.get("PROJECT_COMMENT_ID");

		if (PROJECT_COMMENT_ID != null) {
			setPROJECT_COMMENT_ID(PROJECT_COMMENT_ID);
		}

		Long PROJECT_ID = (Long)attributes.get("PROJECT_ID");

		if (PROJECT_ID != null) {
			setPROJECT_ID(PROJECT_ID);
		}

		String COMMENT = (String)attributes.get("COMMENT");

		if (COMMENT != null) {
			setCOMMENT(COMMENT);
		}

		String ANSWER = (String)attributes.get("ANSWER");

		if (ANSWER != null) {
			setANSWER(ANSWER);
		}

		Long DONOR_USER_ID = (Long)attributes.get("DONOR_USER_ID");

		if (DONOR_USER_ID != null) {
			setDONOR_USER_ID(DONOR_USER_ID);
		}

		Date COMMENT_DATE = (Date)attributes.get("COMMENT_DATE");

		if (COMMENT_DATE != null) {
			setCOMMENT_DATE(COMMENT_DATE);
		}

		Integer STATUS = (Integer)attributes.get("STATUS");

		if (STATUS != null) {
			setSTATUS(STATUS);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPROJECT_COMMENT_ID() {
		return _PROJECT_COMMENT_ID;
	}

	@Override
	public void setPROJECT_COMMENT_ID(long PROJECT_COMMENT_ID) {
		_columnBitmask |= PROJECT_COMMENT_ID_COLUMN_BITMASK;

		if (!_setOriginalPROJECT_COMMENT_ID) {
			_setOriginalPROJECT_COMMENT_ID = true;

			_originalPROJECT_COMMENT_ID = _PROJECT_COMMENT_ID;
		}

		_PROJECT_COMMENT_ID = PROJECT_COMMENT_ID;
	}

	public long getOriginalPROJECT_COMMENT_ID() {
		return _originalPROJECT_COMMENT_ID;
	}

	@JSON
	@Override
	public long getPROJECT_ID() {
		return _PROJECT_ID;
	}

	@Override
	public void setPROJECT_ID(long PROJECT_ID) {
		_columnBitmask |= PROJECT_ID_COLUMN_BITMASK;

		if (!_setOriginalPROJECT_ID) {
			_setOriginalPROJECT_ID = true;

			_originalPROJECT_ID = _PROJECT_ID;
		}

		_PROJECT_ID = PROJECT_ID;
	}

	public long getOriginalPROJECT_ID() {
		return _originalPROJECT_ID;
	}

	@JSON
	@Override
	public String getCOMMENT() {
		if (_COMMENT == null) {
			return "";
		}
		else {
			return _COMMENT;
		}
	}

	@Override
	public void setCOMMENT(String COMMENT) {
		_COMMENT = COMMENT;
	}

	@JSON
	@Override
	public String getANSWER() {
		if (_ANSWER == null) {
			return "";
		}
		else {
			return _ANSWER;
		}
	}

	@Override
	public void setANSWER(String ANSWER) {
		_ANSWER = ANSWER;
	}

	@JSON
	@Override
	public long getDONOR_USER_ID() {
		return _DONOR_USER_ID;
	}

	@Override
	public void setDONOR_USER_ID(long DONOR_USER_ID) {
		_DONOR_USER_ID = DONOR_USER_ID;
	}

	@JSON
	@Override
	public Date getCOMMENT_DATE() {
		return _COMMENT_DATE;
	}

	@Override
	public void setCOMMENT_DATE(Date COMMENT_DATE) {
		_COMMENT_DATE = COMMENT_DATE;
	}

	@JSON
	@Override
	public int getSTATUS() {
		return _STATUS;
	}

	@Override
	public void setSTATUS(int STATUS) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalSTATUS) {
			_setOriginalSTATUS = true;

			_originalSTATUS = _STATUS;
		}

		_STATUS = STATUS;
	}

	public int getOriginalSTATUS() {
		return _originalSTATUS;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CommentRegistration.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommentRegistration toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CommentRegistration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommentRegistrationImpl commentRegistrationImpl = new CommentRegistrationImpl();

		commentRegistrationImpl.setUuid(getUuid());
		commentRegistrationImpl.setPROJECT_COMMENT_ID(getPROJECT_COMMENT_ID());
		commentRegistrationImpl.setPROJECT_ID(getPROJECT_ID());
		commentRegistrationImpl.setCOMMENT(getCOMMENT());
		commentRegistrationImpl.setANSWER(getANSWER());
		commentRegistrationImpl.setDONOR_USER_ID(getDONOR_USER_ID());
		commentRegistrationImpl.setCOMMENT_DATE(getCOMMENT_DATE());
		commentRegistrationImpl.setSTATUS(getSTATUS());

		commentRegistrationImpl.resetOriginalValues();

		return commentRegistrationImpl;
	}

	@Override
	public int compareTo(CommentRegistration commentRegistration) {
		long primaryKey = commentRegistration.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommentRegistration)) {
			return false;
		}

		CommentRegistration commentRegistration = (CommentRegistration)obj;

		long primaryKey = commentRegistration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CommentRegistrationModelImpl commentRegistrationModelImpl = this;

		commentRegistrationModelImpl._originalUuid = commentRegistrationModelImpl._uuid;

		commentRegistrationModelImpl._originalPROJECT_COMMENT_ID = commentRegistrationModelImpl._PROJECT_COMMENT_ID;

		commentRegistrationModelImpl._setOriginalPROJECT_COMMENT_ID = false;

		commentRegistrationModelImpl._originalPROJECT_ID = commentRegistrationModelImpl._PROJECT_ID;

		commentRegistrationModelImpl._setOriginalPROJECT_ID = false;

		commentRegistrationModelImpl._originalSTATUS = commentRegistrationModelImpl._STATUS;

		commentRegistrationModelImpl._setOriginalSTATUS = false;

		commentRegistrationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommentRegistration> toCacheModel() {
		CommentRegistrationCacheModel commentRegistrationCacheModel = new CommentRegistrationCacheModel();

		commentRegistrationCacheModel.uuid = getUuid();

		String uuid = commentRegistrationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			commentRegistrationCacheModel.uuid = null;
		}

		commentRegistrationCacheModel.PROJECT_COMMENT_ID = getPROJECT_COMMENT_ID();

		commentRegistrationCacheModel.PROJECT_ID = getPROJECT_ID();

		commentRegistrationCacheModel.COMMENT = getCOMMENT();

		String COMMENT = commentRegistrationCacheModel.COMMENT;

		if ((COMMENT != null) && (COMMENT.length() == 0)) {
			commentRegistrationCacheModel.COMMENT = null;
		}

		commentRegistrationCacheModel.ANSWER = getANSWER();

		String ANSWER = commentRegistrationCacheModel.ANSWER;

		if ((ANSWER != null) && (ANSWER.length() == 0)) {
			commentRegistrationCacheModel.ANSWER = null;
		}

		commentRegistrationCacheModel.DONOR_USER_ID = getDONOR_USER_ID();

		Date COMMENT_DATE = getCOMMENT_DATE();

		if (COMMENT_DATE != null) {
			commentRegistrationCacheModel.COMMENT_DATE = COMMENT_DATE.getTime();
		}
		else {
			commentRegistrationCacheModel.COMMENT_DATE = Long.MIN_VALUE;
		}

		commentRegistrationCacheModel.STATUS = getSTATUS();

		return commentRegistrationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", PROJECT_COMMENT_ID=");
		sb.append(getPROJECT_COMMENT_ID());
		sb.append(", PROJECT_ID=");
		sb.append(getPROJECT_ID());
		sb.append(", COMMENT=");
		sb.append(getCOMMENT());
		sb.append(", ANSWER=");
		sb.append(getANSWER());
		sb.append(", DONOR_USER_ID=");
		sb.append(getDONOR_USER_ID());
		sb.append(", COMMENT_DATE=");
		sb.append(getCOMMENT_DATE());
		sb.append(", STATUS=");
		sb.append(getSTATUS());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.crowd.funding.database.model.CommentRegistration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PROJECT_COMMENT_ID</column-name><column-value><![CDATA[");
		sb.append(getPROJECT_COMMENT_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PROJECT_ID</column-name><column-value><![CDATA[");
		sb.append(getPROJECT_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>COMMENT</column-name><column-value><![CDATA[");
		sb.append(getCOMMENT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ANSWER</column-name><column-value><![CDATA[");
		sb.append(getANSWER());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DONOR_USER_ID</column-name><column-value><![CDATA[");
		sb.append(getDONOR_USER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>COMMENT_DATE</column-name><column-value><![CDATA[");
		sb.append(getCOMMENT_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>STATUS</column-name><column-value><![CDATA[");
		sb.append(getSTATUS());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CommentRegistration.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CommentRegistration.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _PROJECT_COMMENT_ID;
	private long _originalPROJECT_COMMENT_ID;
	private boolean _setOriginalPROJECT_COMMENT_ID;
	private long _PROJECT_ID;
	private long _originalPROJECT_ID;
	private boolean _setOriginalPROJECT_ID;
	private String _COMMENT;
	private String _ANSWER;
	private long _DONOR_USER_ID;
	private Date _COMMENT_DATE;
	private int _STATUS;
	private int _originalSTATUS;
	private boolean _setOriginalSTATUS;
	private long _columnBitmask;
	private CommentRegistration _escapedModel;
}