/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.crowd.funding.database.model.DonorRegistration;
import com.crowd.funding.database.model.DonorRegistrationModel;
import com.crowd.funding.database.model.DonorRegistrationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DonorRegistration service. Represents a row in the &quot;cf_donor_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DonorRegistrationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DonorRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DonorRegistrationImpl
 * @see DonorRegistration
 * @see DonorRegistrationModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DonorRegistrationModelImpl extends BaseModelImpl<DonorRegistration>
	implements DonorRegistrationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a donor registration model instance should use the {@link DonorRegistration} interface instead.
	 */
	public static final String TABLE_NAME = "cf_donor_details";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "DONOR_ID", Types.BIGINT },
			{ "NAME", Types.VARCHAR },
			{ "ADDRESS", Types.VARCHAR },
			{ "CITY", Types.VARCHAR },
			{ "STATE", Types.VARCHAR },
			{ "COUNTRY", Types.VARCHAR },
			{ "PINCODE", Types.VARCHAR },
			{ "MAIL_ADDRESS", Types.VARCHAR },
			{ "MOBILE_NO", Types.BIGINT },
			{ "OTP", Types.INTEGER },
			{ "MAIL_VERIFICATION", Types.INTEGER },
			{ "SMS_VERIFICATION", Types.INTEGER },
			{ "CREATION_DATE_TIME", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DONOR_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADDRESS", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CITY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("STATE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("COUNTRY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PINCODE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MAIL_ADDRESS", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MOBILE_NO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("OTP", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("MAIL_VERIFICATION", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("SMS_VERIFICATION", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("CREATION_DATE_TIME", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table cf_donor_details (uuid_ VARCHAR(75) null,DONOR_ID LONG not null primary key,NAME VARCHAR(75) null,ADDRESS VARCHAR(75) null,CITY VARCHAR(75) null,STATE VARCHAR(75) null,COUNTRY VARCHAR(75) null,PINCODE VARCHAR(75) null,MAIL_ADDRESS VARCHAR(75) null,MOBILE_NO LONG,OTP INTEGER,MAIL_VERIFICATION INTEGER,SMS_VERIFICATION INTEGER,CREATION_DATE_TIME DATE null)";
	public static final String TABLE_SQL_DROP = "drop table cf_donor_details";
	public static final String ORDER_BY_JPQL = " ORDER BY donorRegistration.DONOR_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY cf_donor_details.DONOR_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.crowd.funding.database.model.DonorRegistration"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.crowd.funding.database.model.DonorRegistration"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.crowd.funding.database.model.DonorRegistration"),
			true);
	public static final long DONOR_ID_COLUMN_BITMASK = 1L;
	public static final long MOBILE_NO_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DonorRegistration toModel(DonorRegistrationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DonorRegistration model = new DonorRegistrationImpl();

		model.setUuid(soapModel.getUuid());
		model.setDONOR_ID(soapModel.getDONOR_ID());
		model.setNAME(soapModel.getNAME());
		model.setADDRESS(soapModel.getADDRESS());
		model.setCITY(soapModel.getCITY());
		model.setSTATE(soapModel.getSTATE());
		model.setCOUNTRY(soapModel.getCOUNTRY());
		model.setPINCODE(soapModel.getPINCODE());
		model.setMAIL_ADDRESS(soapModel.getMAIL_ADDRESS());
		model.setMOBILE_NO(soapModel.getMOBILE_NO());
		model.setOTP(soapModel.getOTP());
		model.setMAIL_VERIFICATION(soapModel.getMAIL_VERIFICATION());
		model.setSMS_VERIFICATION(soapModel.getSMS_VERIFICATION());
		model.setCREATION_DATE_TIME(soapModel.getCREATION_DATE_TIME());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DonorRegistration> toModels(
		DonorRegistrationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DonorRegistration> models = new ArrayList<DonorRegistration>(soapModels.length);

		for (DonorRegistrationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.crowd.funding.database.service.util.ServiceProps.get(
				"lock.expiration.time.com.crowd.funding.database.model.DonorRegistration"));

	public DonorRegistrationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _DONOR_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDONOR_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _DONOR_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DonorRegistration.class;
	}

	@Override
	public String getModelClassName() {
		return DonorRegistration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("DONOR_ID", getDONOR_ID());
		attributes.put("NAME", getNAME());
		attributes.put("ADDRESS", getADDRESS());
		attributes.put("CITY", getCITY());
		attributes.put("STATE", getSTATE());
		attributes.put("COUNTRY", getCOUNTRY());
		attributes.put("PINCODE", getPINCODE());
		attributes.put("MAIL_ADDRESS", getMAIL_ADDRESS());
		attributes.put("MOBILE_NO", getMOBILE_NO());
		attributes.put("OTP", getOTP());
		attributes.put("MAIL_VERIFICATION", getMAIL_VERIFICATION());
		attributes.put("SMS_VERIFICATION", getSMS_VERIFICATION());
		attributes.put("CREATION_DATE_TIME", getCREATION_DATE_TIME());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long DONOR_ID = (Long)attributes.get("DONOR_ID");

		if (DONOR_ID != null) {
			setDONOR_ID(DONOR_ID);
		}

		String NAME = (String)attributes.get("NAME");

		if (NAME != null) {
			setNAME(NAME);
		}

		String ADDRESS = (String)attributes.get("ADDRESS");

		if (ADDRESS != null) {
			setADDRESS(ADDRESS);
		}

		String CITY = (String)attributes.get("CITY");

		if (CITY != null) {
			setCITY(CITY);
		}

		String STATE = (String)attributes.get("STATE");

		if (STATE != null) {
			setSTATE(STATE);
		}

		String COUNTRY = (String)attributes.get("COUNTRY");

		if (COUNTRY != null) {
			setCOUNTRY(COUNTRY);
		}

		String PINCODE = (String)attributes.get("PINCODE");

		if (PINCODE != null) {
			setPINCODE(PINCODE);
		}

		String MAIL_ADDRESS = (String)attributes.get("MAIL_ADDRESS");

		if (MAIL_ADDRESS != null) {
			setMAIL_ADDRESS(MAIL_ADDRESS);
		}

		Long MOBILE_NO = (Long)attributes.get("MOBILE_NO");

		if (MOBILE_NO != null) {
			setMOBILE_NO(MOBILE_NO);
		}

		Integer OTP = (Integer)attributes.get("OTP");

		if (OTP != null) {
			setOTP(OTP);
		}

		Integer MAIL_VERIFICATION = (Integer)attributes.get("MAIL_VERIFICATION");

		if (MAIL_VERIFICATION != null) {
			setMAIL_VERIFICATION(MAIL_VERIFICATION);
		}

		Integer SMS_VERIFICATION = (Integer)attributes.get("SMS_VERIFICATION");

		if (SMS_VERIFICATION != null) {
			setSMS_VERIFICATION(SMS_VERIFICATION);
		}

		Date CREATION_DATE_TIME = (Date)attributes.get("CREATION_DATE_TIME");

		if (CREATION_DATE_TIME != null) {
			setCREATION_DATE_TIME(CREATION_DATE_TIME);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getDONOR_ID() {
		return _DONOR_ID;
	}

	@Override
	public void setDONOR_ID(long DONOR_ID) {
		_columnBitmask |= DONOR_ID_COLUMN_BITMASK;

		if (!_setOriginalDONOR_ID) {
			_setOriginalDONOR_ID = true;

			_originalDONOR_ID = _DONOR_ID;
		}

		_DONOR_ID = DONOR_ID;
	}

	public long getOriginalDONOR_ID() {
		return _originalDONOR_ID;
	}

	@JSON
	@Override
	public String getNAME() {
		if (_NAME == null) {
			return "";
		}
		else {
			return _NAME;
		}
	}

	@Override
	public void setNAME(String NAME) {
		_NAME = NAME;
	}

	@JSON
	@Override
	public String getADDRESS() {
		if (_ADDRESS == null) {
			return "";
		}
		else {
			return _ADDRESS;
		}
	}

	@Override
	public void setADDRESS(String ADDRESS) {
		_ADDRESS = ADDRESS;
	}

	@JSON
	@Override
	public String getCITY() {
		if (_CITY == null) {
			return "";
		}
		else {
			return _CITY;
		}
	}

	@Override
	public void setCITY(String CITY) {
		_CITY = CITY;
	}

	@JSON
	@Override
	public String getSTATE() {
		if (_STATE == null) {
			return "";
		}
		else {
			return _STATE;
		}
	}

	@Override
	public void setSTATE(String STATE) {
		_STATE = STATE;
	}

	@JSON
	@Override
	public String getCOUNTRY() {
		if (_COUNTRY == null) {
			return "";
		}
		else {
			return _COUNTRY;
		}
	}

	@Override
	public void setCOUNTRY(String COUNTRY) {
		_COUNTRY = COUNTRY;
	}

	@JSON
	@Override
	public String getPINCODE() {
		if (_PINCODE == null) {
			return "";
		}
		else {
			return _PINCODE;
		}
	}

	@Override
	public void setPINCODE(String PINCODE) {
		_PINCODE = PINCODE;
	}

	@JSON
	@Override
	public String getMAIL_ADDRESS() {
		if (_MAIL_ADDRESS == null) {
			return "";
		}
		else {
			return _MAIL_ADDRESS;
		}
	}

	@Override
	public void setMAIL_ADDRESS(String MAIL_ADDRESS) {
		_MAIL_ADDRESS = MAIL_ADDRESS;
	}

	@JSON
	@Override
	public long getMOBILE_NO() {
		return _MOBILE_NO;
	}

	@Override
	public void setMOBILE_NO(long MOBILE_NO) {
		_columnBitmask |= MOBILE_NO_COLUMN_BITMASK;

		if (!_setOriginalMOBILE_NO) {
			_setOriginalMOBILE_NO = true;

			_originalMOBILE_NO = _MOBILE_NO;
		}

		_MOBILE_NO = MOBILE_NO;
	}

	public long getOriginalMOBILE_NO() {
		return _originalMOBILE_NO;
	}

	@JSON
	@Override
	public int getOTP() {
		return _OTP;
	}

	@Override
	public void setOTP(int OTP) {
		_OTP = OTP;
	}

	@JSON
	@Override
	public int getMAIL_VERIFICATION() {
		return _MAIL_VERIFICATION;
	}

	@Override
	public void setMAIL_VERIFICATION(int MAIL_VERIFICATION) {
		_MAIL_VERIFICATION = MAIL_VERIFICATION;
	}

	@JSON
	@Override
	public int getSMS_VERIFICATION() {
		return _SMS_VERIFICATION;
	}

	@Override
	public void setSMS_VERIFICATION(int SMS_VERIFICATION) {
		_SMS_VERIFICATION = SMS_VERIFICATION;
	}

	@JSON
	@Override
	public Date getCREATION_DATE_TIME() {
		return _CREATION_DATE_TIME;
	}

	@Override
	public void setCREATION_DATE_TIME(Date CREATION_DATE_TIME) {
		_CREATION_DATE_TIME = CREATION_DATE_TIME;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DonorRegistration.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DonorRegistration toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DonorRegistration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DonorRegistrationImpl donorRegistrationImpl = new DonorRegistrationImpl();

		donorRegistrationImpl.setUuid(getUuid());
		donorRegistrationImpl.setDONOR_ID(getDONOR_ID());
		donorRegistrationImpl.setNAME(getNAME());
		donorRegistrationImpl.setADDRESS(getADDRESS());
		donorRegistrationImpl.setCITY(getCITY());
		donorRegistrationImpl.setSTATE(getSTATE());
		donorRegistrationImpl.setCOUNTRY(getCOUNTRY());
		donorRegistrationImpl.setPINCODE(getPINCODE());
		donorRegistrationImpl.setMAIL_ADDRESS(getMAIL_ADDRESS());
		donorRegistrationImpl.setMOBILE_NO(getMOBILE_NO());
		donorRegistrationImpl.setOTP(getOTP());
		donorRegistrationImpl.setMAIL_VERIFICATION(getMAIL_VERIFICATION());
		donorRegistrationImpl.setSMS_VERIFICATION(getSMS_VERIFICATION());
		donorRegistrationImpl.setCREATION_DATE_TIME(getCREATION_DATE_TIME());

		donorRegistrationImpl.resetOriginalValues();

		return donorRegistrationImpl;
	}

	@Override
	public int compareTo(DonorRegistration donorRegistration) {
		long primaryKey = donorRegistration.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DonorRegistration)) {
			return false;
		}

		DonorRegistration donorRegistration = (DonorRegistration)obj;

		long primaryKey = donorRegistration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DonorRegistrationModelImpl donorRegistrationModelImpl = this;

		donorRegistrationModelImpl._originalUuid = donorRegistrationModelImpl._uuid;

		donorRegistrationModelImpl._originalDONOR_ID = donorRegistrationModelImpl._DONOR_ID;

		donorRegistrationModelImpl._setOriginalDONOR_ID = false;

		donorRegistrationModelImpl._originalMOBILE_NO = donorRegistrationModelImpl._MOBILE_NO;

		donorRegistrationModelImpl._setOriginalMOBILE_NO = false;

		donorRegistrationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DonorRegistration> toCacheModel() {
		DonorRegistrationCacheModel donorRegistrationCacheModel = new DonorRegistrationCacheModel();

		donorRegistrationCacheModel.uuid = getUuid();

		String uuid = donorRegistrationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			donorRegistrationCacheModel.uuid = null;
		}

		donorRegistrationCacheModel.DONOR_ID = getDONOR_ID();

		donorRegistrationCacheModel.NAME = getNAME();

		String NAME = donorRegistrationCacheModel.NAME;

		if ((NAME != null) && (NAME.length() == 0)) {
			donorRegistrationCacheModel.NAME = null;
		}

		donorRegistrationCacheModel.ADDRESS = getADDRESS();

		String ADDRESS = donorRegistrationCacheModel.ADDRESS;

		if ((ADDRESS != null) && (ADDRESS.length() == 0)) {
			donorRegistrationCacheModel.ADDRESS = null;
		}

		donorRegistrationCacheModel.CITY = getCITY();

		String CITY = donorRegistrationCacheModel.CITY;

		if ((CITY != null) && (CITY.length() == 0)) {
			donorRegistrationCacheModel.CITY = null;
		}

		donorRegistrationCacheModel.STATE = getSTATE();

		String STATE = donorRegistrationCacheModel.STATE;

		if ((STATE != null) && (STATE.length() == 0)) {
			donorRegistrationCacheModel.STATE = null;
		}

		donorRegistrationCacheModel.COUNTRY = getCOUNTRY();

		String COUNTRY = donorRegistrationCacheModel.COUNTRY;

		if ((COUNTRY != null) && (COUNTRY.length() == 0)) {
			donorRegistrationCacheModel.COUNTRY = null;
		}

		donorRegistrationCacheModel.PINCODE = getPINCODE();

		String PINCODE = donorRegistrationCacheModel.PINCODE;

		if ((PINCODE != null) && (PINCODE.length() == 0)) {
			donorRegistrationCacheModel.PINCODE = null;
		}

		donorRegistrationCacheModel.MAIL_ADDRESS = getMAIL_ADDRESS();

		String MAIL_ADDRESS = donorRegistrationCacheModel.MAIL_ADDRESS;

		if ((MAIL_ADDRESS != null) && (MAIL_ADDRESS.length() == 0)) {
			donorRegistrationCacheModel.MAIL_ADDRESS = null;
		}

		donorRegistrationCacheModel.MOBILE_NO = getMOBILE_NO();

		donorRegistrationCacheModel.OTP = getOTP();

		donorRegistrationCacheModel.MAIL_VERIFICATION = getMAIL_VERIFICATION();

		donorRegistrationCacheModel.SMS_VERIFICATION = getSMS_VERIFICATION();

		Date CREATION_DATE_TIME = getCREATION_DATE_TIME();

		if (CREATION_DATE_TIME != null) {
			donorRegistrationCacheModel.CREATION_DATE_TIME = CREATION_DATE_TIME.getTime();
		}
		else {
			donorRegistrationCacheModel.CREATION_DATE_TIME = Long.MIN_VALUE;
		}

		return donorRegistrationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", DONOR_ID=");
		sb.append(getDONOR_ID());
		sb.append(", NAME=");
		sb.append(getNAME());
		sb.append(", ADDRESS=");
		sb.append(getADDRESS());
		sb.append(", CITY=");
		sb.append(getCITY());
		sb.append(", STATE=");
		sb.append(getSTATE());
		sb.append(", COUNTRY=");
		sb.append(getCOUNTRY());
		sb.append(", PINCODE=");
		sb.append(getPINCODE());
		sb.append(", MAIL_ADDRESS=");
		sb.append(getMAIL_ADDRESS());
		sb.append(", MOBILE_NO=");
		sb.append(getMOBILE_NO());
		sb.append(", OTP=");
		sb.append(getOTP());
		sb.append(", MAIL_VERIFICATION=");
		sb.append(getMAIL_VERIFICATION());
		sb.append(", SMS_VERIFICATION=");
		sb.append(getSMS_VERIFICATION());
		sb.append(", CREATION_DATE_TIME=");
		sb.append(getCREATION_DATE_TIME());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.crowd.funding.database.model.DonorRegistration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DONOR_ID</column-name><column-value><![CDATA[");
		sb.append(getDONOR_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NAME</column-name><column-value><![CDATA[");
		sb.append(getNAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADDRESS</column-name><column-value><![CDATA[");
		sb.append(getADDRESS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CITY</column-name><column-value><![CDATA[");
		sb.append(getCITY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>STATE</column-name><column-value><![CDATA[");
		sb.append(getSTATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>COUNTRY</column-name><column-value><![CDATA[");
		sb.append(getCOUNTRY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PINCODE</column-name><column-value><![CDATA[");
		sb.append(getPINCODE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MAIL_ADDRESS</column-name><column-value><![CDATA[");
		sb.append(getMAIL_ADDRESS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MOBILE_NO</column-name><column-value><![CDATA[");
		sb.append(getMOBILE_NO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>OTP</column-name><column-value><![CDATA[");
		sb.append(getOTP());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MAIL_VERIFICATION</column-name><column-value><![CDATA[");
		sb.append(getMAIL_VERIFICATION());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SMS_VERIFICATION</column-name><column-value><![CDATA[");
		sb.append(getSMS_VERIFICATION());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CREATION_DATE_TIME</column-name><column-value><![CDATA[");
		sb.append(getCREATION_DATE_TIME());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = DonorRegistration.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			DonorRegistration.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _DONOR_ID;
	private long _originalDONOR_ID;
	private boolean _setOriginalDONOR_ID;
	private String _NAME;
	private String _ADDRESS;
	private String _CITY;
	private String _STATE;
	private String _COUNTRY;
	private String _PINCODE;
	private String _MAIL_ADDRESS;
	private long _MOBILE_NO;
	private long _originalMOBILE_NO;
	private boolean _setOriginalMOBILE_NO;
	private int _OTP;
	private int _MAIL_VERIFICATION;
	private int _SMS_VERIFICATION;
	private Date _CREATION_DATE_TIME;
	private long _columnBitmask;
	private DonorRegistration _escapedModel;
}