/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.crowd.funding.database.model.UpdateRequesterRegistration;
import com.crowd.funding.database.model.UpdateRequesterRegistrationModel;
import com.crowd.funding.database.model.UpdateRequesterRegistrationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UpdateRequesterRegistration service. Represents a row in the &quot;cf_update_requester_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link UpdateRequesterRegistrationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UpdateRequesterRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UpdateRequesterRegistrationImpl
 * @see UpdateRequesterRegistration
 * @see UpdateRequesterRegistrationModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class UpdateRequesterRegistrationModelImpl extends BaseModelImpl<UpdateRequesterRegistration>
	implements UpdateRequesterRegistrationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a update requester registration model instance should use the {@link UpdateRequesterRegistration} interface instead.
	 */
	public static final String TABLE_NAME = "cf_update_requester_details";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "PROJECT_UPDATE_REQUEST_ID", Types.BIGINT },
			{ "PROJECT_ID", Types.BIGINT },
			{ "UPDATE_REQUESTER_USER_ID", Types.BIGINT },
			{ "UPDATE_REQUEST_DATE", Types.TIMESTAMP },
			{ "STATUS", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PROJECT_UPDATE_REQUEST_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("PROJECT_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("UPDATE_REQUESTER_USER_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("UPDATE_REQUEST_DATE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("STATUS", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table cf_update_requester_details (uuid_ VARCHAR(75) null,PROJECT_UPDATE_REQUEST_ID LONG not null primary key,PROJECT_ID LONG,UPDATE_REQUESTER_USER_ID LONG,UPDATE_REQUEST_DATE DATE null,STATUS INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table cf_update_requester_details";
	public static final String ORDER_BY_JPQL = " ORDER BY updateRequesterRegistration.PROJECT_UPDATE_REQUEST_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY cf_update_requester_details.PROJECT_UPDATE_REQUEST_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.crowd.funding.database.model.UpdateRequesterRegistration"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.crowd.funding.database.model.UpdateRequesterRegistration"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.crowd.funding.database.model.UpdateRequesterRegistration"),
			true);
	public static final long PROJECT_ID_COLUMN_BITMASK = 1L;
	public static final long PROJECT_UPDATE_REQUEST_ID_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UpdateRequesterRegistration toModel(
		UpdateRequesterRegistrationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UpdateRequesterRegistration model = new UpdateRequesterRegistrationImpl();

		model.setUuid(soapModel.getUuid());
		model.setPROJECT_UPDATE_REQUEST_ID(soapModel.getPROJECT_UPDATE_REQUEST_ID());
		model.setPROJECT_ID(soapModel.getPROJECT_ID());
		model.setUPDATE_REQUESTER_USER_ID(soapModel.getUPDATE_REQUESTER_USER_ID());
		model.setUPDATE_REQUEST_DATE(soapModel.getUPDATE_REQUEST_DATE());
		model.setSTATUS(soapModel.getSTATUS());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UpdateRequesterRegistration> toModels(
		UpdateRequesterRegistrationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UpdateRequesterRegistration> models = new ArrayList<UpdateRequesterRegistration>(soapModels.length);

		for (UpdateRequesterRegistrationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.crowd.funding.database.service.util.ServiceProps.get(
				"lock.expiration.time.com.crowd.funding.database.model.UpdateRequesterRegistration"));

	public UpdateRequesterRegistrationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PROJECT_UPDATE_REQUEST_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPROJECT_UPDATE_REQUEST_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PROJECT_UPDATE_REQUEST_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UpdateRequesterRegistration.class;
	}

	@Override
	public String getModelClassName() {
		return UpdateRequesterRegistration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("PROJECT_UPDATE_REQUEST_ID",
			getPROJECT_UPDATE_REQUEST_ID());
		attributes.put("PROJECT_ID", getPROJECT_ID());
		attributes.put("UPDATE_REQUESTER_USER_ID", getUPDATE_REQUESTER_USER_ID());
		attributes.put("UPDATE_REQUEST_DATE", getUPDATE_REQUEST_DATE());
		attributes.put("STATUS", getSTATUS());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long PROJECT_UPDATE_REQUEST_ID = (Long)attributes.get(
				"PROJECT_UPDATE_REQUEST_ID");

		if (PROJECT_UPDATE_REQUEST_ID != null) {
			setPROJECT_UPDATE_REQUEST_ID(PROJECT_UPDATE_REQUEST_ID);
		}

		Long PROJECT_ID = (Long)attributes.get("PROJECT_ID");

		if (PROJECT_ID != null) {
			setPROJECT_ID(PROJECT_ID);
		}

		Long UPDATE_REQUESTER_USER_ID = (Long)attributes.get(
				"UPDATE_REQUESTER_USER_ID");

		if (UPDATE_REQUESTER_USER_ID != null) {
			setUPDATE_REQUESTER_USER_ID(UPDATE_REQUESTER_USER_ID);
		}

		Date UPDATE_REQUEST_DATE = (Date)attributes.get("UPDATE_REQUEST_DATE");

		if (UPDATE_REQUEST_DATE != null) {
			setUPDATE_REQUEST_DATE(UPDATE_REQUEST_DATE);
		}

		Integer STATUS = (Integer)attributes.get("STATUS");

		if (STATUS != null) {
			setSTATUS(STATUS);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPROJECT_UPDATE_REQUEST_ID() {
		return _PROJECT_UPDATE_REQUEST_ID;
	}

	@Override
	public void setPROJECT_UPDATE_REQUEST_ID(long PROJECT_UPDATE_REQUEST_ID) {
		_columnBitmask |= PROJECT_UPDATE_REQUEST_ID_COLUMN_BITMASK;

		if (!_setOriginalPROJECT_UPDATE_REQUEST_ID) {
			_setOriginalPROJECT_UPDATE_REQUEST_ID = true;

			_originalPROJECT_UPDATE_REQUEST_ID = _PROJECT_UPDATE_REQUEST_ID;
		}

		_PROJECT_UPDATE_REQUEST_ID = PROJECT_UPDATE_REQUEST_ID;
	}

	public long getOriginalPROJECT_UPDATE_REQUEST_ID() {
		return _originalPROJECT_UPDATE_REQUEST_ID;
	}

	@JSON
	@Override
	public long getPROJECT_ID() {
		return _PROJECT_ID;
	}

	@Override
	public void setPROJECT_ID(long PROJECT_ID) {
		_columnBitmask |= PROJECT_ID_COLUMN_BITMASK;

		if (!_setOriginalPROJECT_ID) {
			_setOriginalPROJECT_ID = true;

			_originalPROJECT_ID = _PROJECT_ID;
		}

		_PROJECT_ID = PROJECT_ID;
	}

	public long getOriginalPROJECT_ID() {
		return _originalPROJECT_ID;
	}

	@JSON
	@Override
	public long getUPDATE_REQUESTER_USER_ID() {
		return _UPDATE_REQUESTER_USER_ID;
	}

	@Override
	public void setUPDATE_REQUESTER_USER_ID(long UPDATE_REQUESTER_USER_ID) {
		_UPDATE_REQUESTER_USER_ID = UPDATE_REQUESTER_USER_ID;
	}

	@JSON
	@Override
	public Date getUPDATE_REQUEST_DATE() {
		return _UPDATE_REQUEST_DATE;
	}

	@Override
	public void setUPDATE_REQUEST_DATE(Date UPDATE_REQUEST_DATE) {
		_UPDATE_REQUEST_DATE = UPDATE_REQUEST_DATE;
	}

	@JSON
	@Override
	public int getSTATUS() {
		return _STATUS;
	}

	@Override
	public void setSTATUS(int STATUS) {
		_STATUS = STATUS;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			UpdateRequesterRegistration.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UpdateRequesterRegistration toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UpdateRequesterRegistration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UpdateRequesterRegistrationImpl updateRequesterRegistrationImpl = new UpdateRequesterRegistrationImpl();

		updateRequesterRegistrationImpl.setUuid(getUuid());
		updateRequesterRegistrationImpl.setPROJECT_UPDATE_REQUEST_ID(getPROJECT_UPDATE_REQUEST_ID());
		updateRequesterRegistrationImpl.setPROJECT_ID(getPROJECT_ID());
		updateRequesterRegistrationImpl.setUPDATE_REQUESTER_USER_ID(getUPDATE_REQUESTER_USER_ID());
		updateRequesterRegistrationImpl.setUPDATE_REQUEST_DATE(getUPDATE_REQUEST_DATE());
		updateRequesterRegistrationImpl.setSTATUS(getSTATUS());

		updateRequesterRegistrationImpl.resetOriginalValues();

		return updateRequesterRegistrationImpl;
	}

	@Override
	public int compareTo(
		UpdateRequesterRegistration updateRequesterRegistration) {
		long primaryKey = updateRequesterRegistration.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UpdateRequesterRegistration)) {
			return false;
		}

		UpdateRequesterRegistration updateRequesterRegistration = (UpdateRequesterRegistration)obj;

		long primaryKey = updateRequesterRegistration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		UpdateRequesterRegistrationModelImpl updateRequesterRegistrationModelImpl =
			this;

		updateRequesterRegistrationModelImpl._originalUuid = updateRequesterRegistrationModelImpl._uuid;

		updateRequesterRegistrationModelImpl._originalPROJECT_UPDATE_REQUEST_ID = updateRequesterRegistrationModelImpl._PROJECT_UPDATE_REQUEST_ID;

		updateRequesterRegistrationModelImpl._setOriginalPROJECT_UPDATE_REQUEST_ID = false;

		updateRequesterRegistrationModelImpl._originalPROJECT_ID = updateRequesterRegistrationModelImpl._PROJECT_ID;

		updateRequesterRegistrationModelImpl._setOriginalPROJECT_ID = false;

		updateRequesterRegistrationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<UpdateRequesterRegistration> toCacheModel() {
		UpdateRequesterRegistrationCacheModel updateRequesterRegistrationCacheModel =
			new UpdateRequesterRegistrationCacheModel();

		updateRequesterRegistrationCacheModel.uuid = getUuid();

		String uuid = updateRequesterRegistrationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			updateRequesterRegistrationCacheModel.uuid = null;
		}

		updateRequesterRegistrationCacheModel.PROJECT_UPDATE_REQUEST_ID = getPROJECT_UPDATE_REQUEST_ID();

		updateRequesterRegistrationCacheModel.PROJECT_ID = getPROJECT_ID();

		updateRequesterRegistrationCacheModel.UPDATE_REQUESTER_USER_ID = getUPDATE_REQUESTER_USER_ID();

		Date UPDATE_REQUEST_DATE = getUPDATE_REQUEST_DATE();

		if (UPDATE_REQUEST_DATE != null) {
			updateRequesterRegistrationCacheModel.UPDATE_REQUEST_DATE = UPDATE_REQUEST_DATE.getTime();
		}
		else {
			updateRequesterRegistrationCacheModel.UPDATE_REQUEST_DATE = Long.MIN_VALUE;
		}

		updateRequesterRegistrationCacheModel.STATUS = getSTATUS();

		return updateRequesterRegistrationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", PROJECT_UPDATE_REQUEST_ID=");
		sb.append(getPROJECT_UPDATE_REQUEST_ID());
		sb.append(", PROJECT_ID=");
		sb.append(getPROJECT_ID());
		sb.append(", UPDATE_REQUESTER_USER_ID=");
		sb.append(getUPDATE_REQUESTER_USER_ID());
		sb.append(", UPDATE_REQUEST_DATE=");
		sb.append(getUPDATE_REQUEST_DATE());
		sb.append(", STATUS=");
		sb.append(getSTATUS());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append(
			"com.crowd.funding.database.model.UpdateRequesterRegistration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PROJECT_UPDATE_REQUEST_ID</column-name><column-value><![CDATA[");
		sb.append(getPROJECT_UPDATE_REQUEST_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PROJECT_ID</column-name><column-value><![CDATA[");
		sb.append(getPROJECT_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATE_REQUESTER_USER_ID</column-name><column-value><![CDATA[");
		sb.append(getUPDATE_REQUESTER_USER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UPDATE_REQUEST_DATE</column-name><column-value><![CDATA[");
		sb.append(getUPDATE_REQUEST_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>STATUS</column-name><column-value><![CDATA[");
		sb.append(getSTATUS());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = UpdateRequesterRegistration.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			UpdateRequesterRegistration.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _PROJECT_UPDATE_REQUEST_ID;
	private long _originalPROJECT_UPDATE_REQUEST_ID;
	private boolean _setOriginalPROJECT_UPDATE_REQUEST_ID;
	private long _PROJECT_ID;
	private long _originalPROJECT_ID;
	private boolean _setOriginalPROJECT_ID;
	private long _UPDATE_REQUESTER_USER_ID;
	private Date _UPDATE_REQUEST_DATE;
	private int _STATUS;
	private long _columnBitmask;
	private UpdateRequesterRegistration _escapedModel;
}