/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

/**
 * The base model interface for the DocumentRegistration service. Represents a row in the &quot;cf_project_document_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.DocumentRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.DocumentRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentRegistration
 * @see com.crowd.funding.database.model.impl.DocumentRegistrationImpl
 * @see com.crowd.funding.database.model.impl.DocumentRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface DocumentRegistrationModel extends BaseModel<DocumentRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document registration model instance should use the {@link DocumentRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this document registration.
	 *
	 * @return the primary key of this document registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document registration.
	 *
	 * @param primaryKey the primary key of this document registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this document registration.
	 *
	 * @return the uuid of this document registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this document registration.
	 *
	 * @param uuid the uuid of this document registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_document_id of this document registration.
	 *
	 * @return the project_document_id of this document registration
	 */
	public long getPROJECT_DOCUMENT_ID();

	/**
	 * Sets the project_document_id of this document registration.
	 *
	 * @param PROJECT_DOCUMENT_ID the project_document_id of this document registration
	 */
	public void setPROJECT_DOCUMENT_ID(long PROJECT_DOCUMENT_ID);

	/**
	 * Returns the project_id of this document registration.
	 *
	 * @return the project_id of this document registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this document registration.
	 *
	 * @param PROJECT_ID the project_id of this document registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the document_name of this document registration.
	 *
	 * @return the document_name of this document registration
	 */
	@AutoEscape
	public String getDOCUMENT_NAME();

	/**
	 * Sets the document_name of this document registration.
	 *
	 * @param DOCUMENT_NAME the document_name of this document registration
	 */
	public void setDOCUMENT_NAME(String DOCUMENT_NAME);

	/**
	 * Returns the document_type of this document registration.
	 *
	 * @return the document_type of this document registration
	 */
	@AutoEscape
	public String getDOCUMENT_TYPE();

	/**
	 * Sets the document_type of this document registration.
	 *
	 * @param DOCUMENT_TYPE the document_type of this document registration
	 */
	public void setDOCUMENT_TYPE(String DOCUMENT_TYPE);

	/**
	 * Returns the document of this document registration.
	 *
	 * @return the document of this document registration
	 */
	public Blob getDOCUMENT();

	/**
	 * Sets the document of this document registration.
	 *
	 * @param DOCUMENT the document of this document registration
	 */
	public void setDOCUMENT(Blob DOCUMENT);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DocumentRegistration documentRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DocumentRegistration> toCacheModel();

	@Override
	public DocumentRegistration toEscapedModel();

	@Override
	public DocumentRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}