/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FundRegistration service. Represents a row in the &quot;cf_project_fund_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.FundRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.FundRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FundRegistration
 * @see com.crowd.funding.database.model.impl.FundRegistrationImpl
 * @see com.crowd.funding.database.model.impl.FundRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface FundRegistrationModel extends BaseModel<FundRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fund registration model instance should use the {@link FundRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this fund registration.
	 *
	 * @return the primary key of this fund registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fund registration.
	 *
	 * @param primaryKey the primary key of this fund registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this fund registration.
	 *
	 * @return the uuid of this fund registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this fund registration.
	 *
	 * @param uuid the uuid of this fund registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_fund_id of this fund registration.
	 *
	 * @return the project_fund_id of this fund registration
	 */
	public long getPROJECT_FUND_ID();

	/**
	 * Sets the project_fund_id of this fund registration.
	 *
	 * @param PROJECT_FUND_ID the project_fund_id of this fund registration
	 */
	public void setPROJECT_FUND_ID(long PROJECT_FUND_ID);

	/**
	 * Returns the donor_id of this fund registration.
	 *
	 * @return the donor_id of this fund registration
	 */
	public long getDONOR_ID();

	/**
	 * Sets the donor_id of this fund registration.
	 *
	 * @param DONOR_ID the donor_id of this fund registration
	 */
	public void setDONOR_ID(long DONOR_ID);

	/**
	 * Returns the project_id of this fund registration.
	 *
	 * @return the project_id of this fund registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this fund registration.
	 *
	 * @param PROJECT_ID the project_id of this fund registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the category_id of this fund registration.
	 *
	 * @return the category_id of this fund registration
	 */
	public long getCATEGORY_ID();

	/**
	 * Sets the category_id of this fund registration.
	 *
	 * @param CATEGORY_ID the category_id of this fund registration
	 */
	public void setCATEGORY_ID(long CATEGORY_ID);

	/**
	 * Returns the currency of this fund registration.
	 *
	 * @return the currency of this fund registration
	 */
	@AutoEscape
	public String getCURRENCY();

	/**
	 * Sets the currency of this fund registration.
	 *
	 * @param CURRENCY the currency of this fund registration
	 */
	public void setCURRENCY(String CURRENCY);

	/**
	 * Returns the donated_amount of this fund registration.
	 *
	 * @return the donated_amount of this fund registration
	 */
	public float getDONATED_AMOUNT();

	/**
	 * Sets the donated_amount of this fund registration.
	 *
	 * @param DONATED_AMOUNT the donated_amount of this fund registration
	 */
	public void setDONATED_AMOUNT(float DONATED_AMOUNT);

	/**
	 * Returns the donor_user_id of this fund registration.
	 *
	 * @return the donor_user_id of this fund registration
	 */
	public long getDONOR_USER_ID();

	/**
	 * Sets the donor_user_id of this fund registration.
	 *
	 * @param DONOR_USER_ID the donor_user_id of this fund registration
	 */
	public void setDONOR_USER_ID(long DONOR_USER_ID);

	/**
	 * Returns the donor_status of this fund registration.
	 *
	 * @return the donor_status of this fund registration
	 */
	public int getDONOR_STATUS();

	/**
	 * Sets the donor_status of this fund registration.
	 *
	 * @param DONOR_STATUS the donor_status of this fund registration
	 */
	public void setDONOR_STATUS(int DONOR_STATUS);

	/**
	 * Returns the comment of this fund registration.
	 *
	 * @return the comment of this fund registration
	 */
	@AutoEscape
	public String getCOMMENT();

	/**
	 * Sets the comment of this fund registration.
	 *
	 * @param COMMENT the comment of this fund registration
	 */
	public void setCOMMENT(String COMMENT);

	/**
	 * Returns the donated_date of this fund registration.
	 *
	 * @return the donated_date of this fund registration
	 */
	public Date getDONATED_DATE();

	/**
	 * Sets the donated_date of this fund registration.
	 *
	 * @param DONATED_DATE the donated_date of this fund registration
	 */
	public void setDONATED_DATE(Date DONATED_DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FundRegistration fundRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FundRegistration> toCacheModel();

	@Override
	public FundRegistration toEscapedModel();

	@Override
	public FundRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}