/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

/**
 * The base model interface for the ImageRegistration service. Represents a row in the &quot;cf_project_image_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.ImageRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.ImageRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ImageRegistration
 * @see com.crowd.funding.database.model.impl.ImageRegistrationImpl
 * @see com.crowd.funding.database.model.impl.ImageRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface ImageRegistrationModel extends BaseModel<ImageRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a image registration model instance should use the {@link ImageRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this image registration.
	 *
	 * @return the primary key of this image registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this image registration.
	 *
	 * @param primaryKey the primary key of this image registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this image registration.
	 *
	 * @return the uuid of this image registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this image registration.
	 *
	 * @param uuid the uuid of this image registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_image_id of this image registration.
	 *
	 * @return the project_image_id of this image registration
	 */
	public long getPROJECT_IMAGE_ID();

	/**
	 * Sets the project_image_id of this image registration.
	 *
	 * @param PROJECT_IMAGE_ID the project_image_id of this image registration
	 */
	public void setPROJECT_IMAGE_ID(long PROJECT_IMAGE_ID);

	/**
	 * Returns the project_id of this image registration.
	 *
	 * @return the project_id of this image registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this image registration.
	 *
	 * @param PROJECT_ID the project_id of this image registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the image_name of this image registration.
	 *
	 * @return the image_name of this image registration
	 */
	@AutoEscape
	public String getIMAGE_NAME();

	/**
	 * Sets the image_name of this image registration.
	 *
	 * @param IMAGE_NAME the image_name of this image registration
	 */
	public void setIMAGE_NAME(String IMAGE_NAME);

	/**
	 * Returns the image_type of this image registration.
	 *
	 * @return the image_type of this image registration
	 */
	@AutoEscape
	public String getIMAGE_TYPE();

	/**
	 * Sets the image_type of this image registration.
	 *
	 * @param IMAGE_TYPE the image_type of this image registration
	 */
	public void setIMAGE_TYPE(String IMAGE_TYPE);

	/**
	 * Returns the image of this image registration.
	 *
	 * @return the image of this image registration
	 */
	public Blob getIMAGE();

	/**
	 * Sets the image of this image registration.
	 *
	 * @param IMAGE the image of this image registration
	 */
	public void setIMAGE(Blob IMAGE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ImageRegistration imageRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ImageRegistration> toCacheModel();

	@Override
	public ImageRegistration toEscapedModel();

	@Override
	public ImageRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}