/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ProjectPriorityRegistration service. Represents a row in the &quot;cf_project_priority_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.ProjectPriorityRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.ProjectPriorityRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectPriorityRegistration
 * @see com.crowd.funding.database.model.impl.ProjectPriorityRegistrationImpl
 * @see com.crowd.funding.database.model.impl.ProjectPriorityRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface ProjectPriorityRegistrationModel extends BaseModel<ProjectPriorityRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project priority registration model instance should use the {@link ProjectPriorityRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this project priority registration.
	 *
	 * @return the primary key of this project priority registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project priority registration.
	 *
	 * @param primaryKey the primary key of this project priority registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project priority registration.
	 *
	 * @return the uuid of this project priority registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this project priority registration.
	 *
	 * @param uuid the uuid of this project priority registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_priority_id of this project priority registration.
	 *
	 * @return the project_priority_id of this project priority registration
	 */
	public long getPROJECT_PRIORITY_ID();

	/**
	 * Sets the project_priority_id of this project priority registration.
	 *
	 * @param PROJECT_PRIORITY_ID the project_priority_id of this project priority registration
	 */
	public void setPROJECT_PRIORITY_ID(long PROJECT_PRIORITY_ID);

	/**
	 * Returns the project_id of this project priority registration.
	 *
	 * @return the project_id of this project priority registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this project priority registration.
	 *
	 * @param PROJECT_ID the project_id of this project priority registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the priority of this project priority registration.
	 *
	 * @return the priority of this project priority registration
	 */
	public int getPRIORITY();

	/**
	 * Sets the priority of this project priority registration.
	 *
	 * @param PRIORITY the priority of this project priority registration
	 */
	public void setPRIORITY(int PRIORITY);

	/**
	 * Returns the priority_sequance of this project priority registration.
	 *
	 * @return the priority_sequance of this project priority registration
	 */
	public int getPRIORITY_SEQUANCE();

	/**
	 * Sets the priority_sequance of this project priority registration.
	 *
	 * @param PRIORITY_SEQUANCE the priority_sequance of this project priority registration
	 */
	public void setPRIORITY_SEQUANCE(int PRIORITY_SEQUANCE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ProjectPriorityRegistration projectPriorityRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectPriorityRegistration> toCacheModel();

	@Override
	public ProjectPriorityRegistration toEscapedModel();

	@Override
	public ProjectPriorityRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}