/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ProjectFollowerRegistration service. Represents a row in the &quot;cf_project_follower_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.ProjectFollowerRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.ProjectFollowerRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectFollowerRegistration
 * @see com.crowd.funding.database.model.impl.ProjectFollowerRegistrationImpl
 * @see com.crowd.funding.database.model.impl.ProjectFollowerRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface ProjectFollowerRegistrationModel extends BaseModel<ProjectFollowerRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project follower registration model instance should use the {@link ProjectFollowerRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this project follower registration.
	 *
	 * @return the primary key of this project follower registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project follower registration.
	 *
	 * @param primaryKey the primary key of this project follower registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project follower registration.
	 *
	 * @return the uuid of this project follower registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this project follower registration.
	 *
	 * @param uuid the uuid of this project follower registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_follower_id of this project follower registration.
	 *
	 * @return the project_follower_id of this project follower registration
	 */
	public long getPROJECT_FOLLOWER_ID();

	/**
	 * Sets the project_follower_id of this project follower registration.
	 *
	 * @param PROJECT_FOLLOWER_ID the project_follower_id of this project follower registration
	 */
	public void setPROJECT_FOLLOWER_ID(long PROJECT_FOLLOWER_ID);

	/**
	 * Returns the user_id of this project follower registration.
	 *
	 * @return the user_id of this project follower registration
	 */
	public long getUSER_ID();

	/**
	 * Sets the user_id of this project follower registration.
	 *
	 * @param USER_ID the user_id of this project follower registration
	 */
	public void setUSER_ID(long USER_ID);

	/**
	 * Returns the project_id of this project follower registration.
	 *
	 * @return the project_id of this project follower registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this project follower registration.
	 *
	 * @param PROJECT_ID the project_id of this project follower registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the status of this project follower registration.
	 *
	 * @return the status of this project follower registration
	 */
	public int getSTATUS();

	/**
	 * Sets the status of this project follower registration.
	 *
	 * @param STATUS the status of this project follower registration
	 */
	public void setSTATUS(int STATUS);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ProjectFollowerRegistration projectFollowerRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectFollowerRegistration> toCacheModel();

	@Override
	public ProjectFollowerRegistration toEscapedModel();

	@Override
	public ProjectFollowerRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}