/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SubscriptionRegistration service. Represents a row in the &quot;cf_subscription_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.SubscriptionRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.SubscriptionRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubscriptionRegistration
 * @see com.crowd.funding.database.model.impl.SubscriptionRegistrationImpl
 * @see com.crowd.funding.database.model.impl.SubscriptionRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface SubscriptionRegistrationModel extends BaseModel<SubscriptionRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subscription registration model instance should use the {@link SubscriptionRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this subscription registration.
	 *
	 * @return the primary key of this subscription registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subscription registration.
	 *
	 * @param primaryKey the primary key of this subscription registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this subscription registration.
	 *
	 * @return the uuid of this subscription registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this subscription registration.
	 *
	 * @param uuid the uuid of this subscription registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the suscriber_id of this subscription registration.
	 *
	 * @return the suscriber_id of this subscription registration
	 */
	public long getSUSCRIBER_ID();

	/**
	 * Sets the suscriber_id of this subscription registration.
	 *
	 * @param SUSCRIBER_ID the suscriber_id of this subscription registration
	 */
	public void setSUSCRIBER_ID(long SUSCRIBER_ID);

	/**
	 * Returns the email of this subscription registration.
	 *
	 * @return the email of this subscription registration
	 */
	@AutoEscape
	public String getEMAIL();

	/**
	 * Sets the email of this subscription registration.
	 *
	 * @param EMAIL the email of this subscription registration
	 */
	public void setEMAIL(String EMAIL);

	/**
	 * Returns the status of this subscription registration.
	 *
	 * @return the status of this subscription registration
	 */
	public int getSTATUS();

	/**
	 * Sets the status of this subscription registration.
	 *
	 * @param STATUS the status of this subscription registration
	 */
	public void setSTATUS(int STATUS);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SubscriptionRegistration subscriptionRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SubscriptionRegistration> toCacheModel();

	@Override
	public SubscriptionRegistration toEscapedModel();

	@Override
	public SubscriptionRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}