/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UpdateRequesterRegistration service. Represents a row in the &quot;cf_update_requester_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.UpdateRequesterRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.UpdateRequesterRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UpdateRequesterRegistration
 * @see com.crowd.funding.database.model.impl.UpdateRequesterRegistrationImpl
 * @see com.crowd.funding.database.model.impl.UpdateRequesterRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface UpdateRequesterRegistrationModel extends BaseModel<UpdateRequesterRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a update requester registration model instance should use the {@link UpdateRequesterRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this update requester registration.
	 *
	 * @return the primary key of this update requester registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this update requester registration.
	 *
	 * @param primaryKey the primary key of this update requester registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this update requester registration.
	 *
	 * @return the uuid of this update requester registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this update requester registration.
	 *
	 * @param uuid the uuid of this update requester registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_update_request_id of this update requester registration.
	 *
	 * @return the project_update_request_id of this update requester registration
	 */
	public long getPROJECT_UPDATE_REQUEST_ID();

	/**
	 * Sets the project_update_request_id of this update requester registration.
	 *
	 * @param PROJECT_UPDATE_REQUEST_ID the project_update_request_id of this update requester registration
	 */
	public void setPROJECT_UPDATE_REQUEST_ID(long PROJECT_UPDATE_REQUEST_ID);

	/**
	 * Returns the project_id of this update requester registration.
	 *
	 * @return the project_id of this update requester registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this update requester registration.
	 *
	 * @param PROJECT_ID the project_id of this update requester registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the update_requester_user_id of this update requester registration.
	 *
	 * @return the update_requester_user_id of this update requester registration
	 */
	public long getUPDATE_REQUESTER_USER_ID();

	/**
	 * Sets the update_requester_user_id of this update requester registration.
	 *
	 * @param UPDATE_REQUESTER_USER_ID the update_requester_user_id of this update requester registration
	 */
	public void setUPDATE_REQUESTER_USER_ID(long UPDATE_REQUESTER_USER_ID);

	/**
	 * Returns the update_request_date of this update requester registration.
	 *
	 * @return the update_request_date of this update requester registration
	 */
	public Date getUPDATE_REQUEST_DATE();

	/**
	 * Sets the update_request_date of this update requester registration.
	 *
	 * @param UPDATE_REQUEST_DATE the update_request_date of this update requester registration
	 */
	public void setUPDATE_REQUEST_DATE(Date UPDATE_REQUEST_DATE);

	/**
	 * Returns the status of this update requester registration.
	 *
	 * @return the status of this update requester registration
	 */
	public int getSTATUS();

	/**
	 * Sets the status of this update requester registration.
	 *
	 * @param STATUS the status of this update requester registration
	 */
	public void setSTATUS(int STATUS);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		UpdateRequesterRegistration updateRequesterRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UpdateRequesterRegistration> toCacheModel();

	@Override
	public UpdateRequesterRegistration toEscapedModel();

	@Override
	public UpdateRequesterRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}