/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserOTPRegistration service. Represents a row in the &quot;cf_user_otp_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.UserOTPRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.UserOTPRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserOTPRegistration
 * @see com.crowd.funding.database.model.impl.UserOTPRegistrationImpl
 * @see com.crowd.funding.database.model.impl.UserOTPRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface UserOTPRegistrationModel extends BaseModel<UserOTPRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user otp registration model instance should use the {@link UserOTPRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this user otp registration.
	 *
	 * @return the primary key of this user otp registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user otp registration.
	 *
	 * @param primaryKey the primary key of this user otp registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user otp registration.
	 *
	 * @return the uuid of this user otp registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user otp registration.
	 *
	 * @param uuid the uuid of this user otp registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user_otp_id of this user otp registration.
	 *
	 * @return the user_otp_id of this user otp registration
	 */
	public long getUSER_OTP_ID();

	/**
	 * Sets the user_otp_id of this user otp registration.
	 *
	 * @param USER_OTP_ID the user_otp_id of this user otp registration
	 */
	public void setUSER_OTP_ID(long USER_OTP_ID);

	/**
	 * Returns the mobile_no of this user otp registration.
	 *
	 * @return the mobile_no of this user otp registration
	 */
	public long getMOBILE_NO();

	/**
	 * Sets the mobile_no of this user otp registration.
	 *
	 * @param MOBILE_NO the mobile_no of this user otp registration
	 */
	public void setMOBILE_NO(long MOBILE_NO);

	/**
	 * Returns the mail of this user otp registration.
	 *
	 * @return the mail of this user otp registration
	 */
	@AutoEscape
	public String getMAIL();

	/**
	 * Sets the mail of this user otp registration.
	 *
	 * @param MAIL the mail of this user otp registration
	 */
	public void setMAIL(String MAIL);

	/**
	 * Returns the otp of this user otp registration.
	 *
	 * @return the otp of this user otp registration
	 */
	public int getOTP();

	/**
	 * Sets the otp of this user otp registration.
	 *
	 * @param OTP the otp of this user otp registration
	 */
	public void setOTP(int OTP);

	/**
	 * Returns the otp_device of this user otp registration.
	 *
	 * @return the otp_device of this user otp registration
	 */
	public int getOTP_DEVICE();

	/**
	 * Sets the otp_device of this user otp registration.
	 *
	 * @param OTP_DEVICE the otp_device of this user otp registration
	 */
	public void setOTP_DEVICE(int OTP_DEVICE);

	/**
	 * Returns the otp_verification_status of this user otp registration.
	 *
	 * @return the otp_verification_status of this user otp registration
	 */
	public int getOTP_VERIFICATION_STATUS();

	/**
	 * Sets the otp_verification_status of this user otp registration.
	 *
	 * @param OTP_VERIFICATION_STATUS the otp_verification_status of this user otp registration
	 */
	public void setOTP_VERIFICATION_STATUS(int OTP_VERIFICATION_STATUS);

	/**
	 * Returns the creation_date_time of this user otp registration.
	 *
	 * @return the creation_date_time of this user otp registration
	 */
	public Date getCREATION_DATE_TIME();

	/**
	 * Sets the creation_date_time of this user otp registration.
	 *
	 * @param CREATION_DATE_TIME the creation_date_time of this user otp registration
	 */
	public void setCREATION_DATE_TIME(Date CREATION_DATE_TIME);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserOTPRegistration userOTPRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserOTPRegistration> toCacheModel();

	@Override
	public UserOTPRegistration toEscapedModel();

	@Override
	public UserOTPRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}