/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserRegistration service. Represents a row in the &quot;cf_user_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.UserRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.UserRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRegistration
 * @see com.crowd.funding.database.model.impl.UserRegistrationImpl
 * @see com.crowd.funding.database.model.impl.UserRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface UserRegistrationModel extends BaseModel<UserRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user registration model instance should use the {@link UserRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this user registration.
	 *
	 * @return the primary key of this user registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user registration.
	 *
	 * @param primaryKey the primary key of this user registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user registration.
	 *
	 * @return the uuid of this user registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user registration.
	 *
	 * @param uuid the uuid of this user registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user_id of this user registration.
	 *
	 * @return the user_id of this user registration
	 */
	public long getUSER_ID();

	/**
	 * Sets the user_id of this user registration.
	 *
	 * @param USER_ID the user_id of this user registration
	 */
	public void setUSER_ID(long USER_ID);

	/**
	 * Returns the user_otp_id of this user registration.
	 *
	 * @return the user_otp_id of this user registration
	 */
	public long getUSER_OTP_ID();

	/**
	 * Sets the user_otp_id of this user registration.
	 *
	 * @param USER_OTP_ID the user_otp_id of this user registration
	 */
	public void setUSER_OTP_ID(long USER_OTP_ID);

	/**
	 * Returns the full_name of this user registration.
	 *
	 * @return the full_name of this user registration
	 */
	@AutoEscape
	public String getFULL_NAME();

	/**
	 * Sets the full_name of this user registration.
	 *
	 * @param FULL_NAME the full_name of this user registration
	 */
	public void setFULL_NAME(String FULL_NAME);

	/**
	 * Returns the password of this user registration.
	 *
	 * @return the password of this user registration
	 */
	@AutoEscape
	public String getPASSWORD();

	/**
	 * Sets the password of this user registration.
	 *
	 * @param PASSWORD the password of this user registration
	 */
	public void setPASSWORD(String PASSWORD);

	/**
	 * Returns the gender of this user registration.
	 *
	 * @return the gender of this user registration
	 */
	@AutoEscape
	public String getGENDER();

	/**
	 * Sets the gender of this user registration.
	 *
	 * @param GENDER the gender of this user registration
	 */
	public void setGENDER(String GENDER);

	/**
	 * Returns the creation_date of this user registration.
	 *
	 * @return the creation_date of this user registration
	 */
	public Date getCREATION_DATE();

	/**
	 * Sets the creation_date of this user registration.
	 *
	 * @param CREATION_DATE the creation_date of this user registration
	 */
	public void setCREATION_DATE(Date CREATION_DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserRegistration userRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserRegistration> toCacheModel();

	@Override
	public UserRegistration toEscapedModel();

	@Override
	public UserRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}