/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.service.base;

import com.crowd.funding.database.model.UserFollowRegistration;
import com.crowd.funding.database.service.UserFollowRegistrationService;
import com.crowd.funding.database.service.persistence.BenificiaryRegistrationPersistence;
import com.crowd.funding.database.service.persistence.CandidateRegistrationPersistence;
import com.crowd.funding.database.service.persistence.CategoryRegistrationPersistence;
import com.crowd.funding.database.service.persistence.CommentRegistrationPersistence;
import com.crowd.funding.database.service.persistence.DocumentRegistrationPersistence;
import com.crowd.funding.database.service.persistence.DonorRegistrationPersistence;
import com.crowd.funding.database.service.persistence.DynamicFeesRegistrationPersistence;
import com.crowd.funding.database.service.persistence.FeedbackRegistrationPersistence;
import com.crowd.funding.database.service.persistence.FundAccountRegistrationPersistence;
import com.crowd.funding.database.service.persistence.FundRegistrationPersistence;
import com.crowd.funding.database.service.persistence.FundReleaseRegistrationPersistence;
import com.crowd.funding.database.service.persistence.HistoryLogRegistrationPersistence;
import com.crowd.funding.database.service.persistence.ImageRegistrationPersistence;
import com.crowd.funding.database.service.persistence.NewsLetterRegistrationPersistence;
import com.crowd.funding.database.service.persistence.PositionRegistrationPersistence;
import com.crowd.funding.database.service.persistence.ProjectAcknowledgementRegistrationPersistence;
import com.crowd.funding.database.service.persistence.ProjectExtentionRegistrationPersistence;
import com.crowd.funding.database.service.persistence.ProjectFeesRegistrationPersistence;
import com.crowd.funding.database.service.persistence.ProjectFollowerRegistrationPersistence;
import com.crowd.funding.database.service.persistence.ProjectPriorityRegistrationPersistence;
import com.crowd.funding.database.service.persistence.ProjectRegistrationFinder;
import com.crowd.funding.database.service.persistence.ProjectRegistrationPersistence;
import com.crowd.funding.database.service.persistence.ProjectUpdateRegistrationPersistence;
import com.crowd.funding.database.service.persistence.QuestionRegistrationPersistence;
import com.crowd.funding.database.service.persistence.SubscriptionRegistrationPersistence;
import com.crowd.funding.database.service.persistence.UpdateRequesterRegistrationPersistence;
import com.crowd.funding.database.service.persistence.UserFollowRegistrationPersistence;
import com.crowd.funding.database.service.persistence.UserOTPRegistrationPersistence;
import com.crowd.funding.database.service.persistence.UserRegistrationPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the user follow registration remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.crowd.funding.database.service.impl.UserFollowRegistrationServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.crowd.funding.database.service.impl.UserFollowRegistrationServiceImpl
 * @see com.crowd.funding.database.service.UserFollowRegistrationServiceUtil
 * @generated
 */
public abstract class UserFollowRegistrationServiceBaseImpl
	extends BaseServiceImpl implements UserFollowRegistrationService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.crowd.funding.database.service.UserFollowRegistrationServiceUtil} to access the user follow registration remote service.
	 */

	/**
	 * Returns the benificiary registration local service.
	 *
	 * @return the benificiary registration local service
	 */
	public com.crowd.funding.database.service.BenificiaryRegistrationLocalService getBenificiaryRegistrationLocalService() {
		return benificiaryRegistrationLocalService;
	}

	/**
	 * Sets the benificiary registration local service.
	 *
	 * @param benificiaryRegistrationLocalService the benificiary registration local service
	 */
	public void setBenificiaryRegistrationLocalService(
		com.crowd.funding.database.service.BenificiaryRegistrationLocalService benificiaryRegistrationLocalService) {
		this.benificiaryRegistrationLocalService = benificiaryRegistrationLocalService;
	}

	/**
	 * Returns the benificiary registration remote service.
	 *
	 * @return the benificiary registration remote service
	 */
	public com.crowd.funding.database.service.BenificiaryRegistrationService getBenificiaryRegistrationService() {
		return benificiaryRegistrationService;
	}

	/**
	 * Sets the benificiary registration remote service.
	 *
	 * @param benificiaryRegistrationService the benificiary registration remote service
	 */
	public void setBenificiaryRegistrationService(
		com.crowd.funding.database.service.BenificiaryRegistrationService benificiaryRegistrationService) {
		this.benificiaryRegistrationService = benificiaryRegistrationService;
	}

	/**
	 * Returns the benificiary registration persistence.
	 *
	 * @return the benificiary registration persistence
	 */
	public BenificiaryRegistrationPersistence getBenificiaryRegistrationPersistence() {
		return benificiaryRegistrationPersistence;
	}

	/**
	 * Sets the benificiary registration persistence.
	 *
	 * @param benificiaryRegistrationPersistence the benificiary registration persistence
	 */
	public void setBenificiaryRegistrationPersistence(
		BenificiaryRegistrationPersistence benificiaryRegistrationPersistence) {
		this.benificiaryRegistrationPersistence = benificiaryRegistrationPersistence;
	}

	/**
	 * Returns the candidate registration local service.
	 *
	 * @return the candidate registration local service
	 */
	public com.crowd.funding.database.service.CandidateRegistrationLocalService getCandidateRegistrationLocalService() {
		return candidateRegistrationLocalService;
	}

	/**
	 * Sets the candidate registration local service.
	 *
	 * @param candidateRegistrationLocalService the candidate registration local service
	 */
	public void setCandidateRegistrationLocalService(
		com.crowd.funding.database.service.CandidateRegistrationLocalService candidateRegistrationLocalService) {
		this.candidateRegistrationLocalService = candidateRegistrationLocalService;
	}

	/**
	 * Returns the candidate registration remote service.
	 *
	 * @return the candidate registration remote service
	 */
	public com.crowd.funding.database.service.CandidateRegistrationService getCandidateRegistrationService() {
		return candidateRegistrationService;
	}

	/**
	 * Sets the candidate registration remote service.
	 *
	 * @param candidateRegistrationService the candidate registration remote service
	 */
	public void setCandidateRegistrationService(
		com.crowd.funding.database.service.CandidateRegistrationService candidateRegistrationService) {
		this.candidateRegistrationService = candidateRegistrationService;
	}

	/**
	 * Returns the candidate registration persistence.
	 *
	 * @return the candidate registration persistence
	 */
	public CandidateRegistrationPersistence getCandidateRegistrationPersistence() {
		return candidateRegistrationPersistence;
	}

	/**
	 * Sets the candidate registration persistence.
	 *
	 * @param candidateRegistrationPersistence the candidate registration persistence
	 */
	public void setCandidateRegistrationPersistence(
		CandidateRegistrationPersistence candidateRegistrationPersistence) {
		this.candidateRegistrationPersistence = candidateRegistrationPersistence;
	}

	/**
	 * Returns the category registration local service.
	 *
	 * @return the category registration local service
	 */
	public com.crowd.funding.database.service.CategoryRegistrationLocalService getCategoryRegistrationLocalService() {
		return categoryRegistrationLocalService;
	}

	/**
	 * Sets the category registration local service.
	 *
	 * @param categoryRegistrationLocalService the category registration local service
	 */
	public void setCategoryRegistrationLocalService(
		com.crowd.funding.database.service.CategoryRegistrationLocalService categoryRegistrationLocalService) {
		this.categoryRegistrationLocalService = categoryRegistrationLocalService;
	}

	/**
	 * Returns the category registration remote service.
	 *
	 * @return the category registration remote service
	 */
	public com.crowd.funding.database.service.CategoryRegistrationService getCategoryRegistrationService() {
		return categoryRegistrationService;
	}

	/**
	 * Sets the category registration remote service.
	 *
	 * @param categoryRegistrationService the category registration remote service
	 */
	public void setCategoryRegistrationService(
		com.crowd.funding.database.service.CategoryRegistrationService categoryRegistrationService) {
		this.categoryRegistrationService = categoryRegistrationService;
	}

	/**
	 * Returns the category registration persistence.
	 *
	 * @return the category registration persistence
	 */
	public CategoryRegistrationPersistence getCategoryRegistrationPersistence() {
		return categoryRegistrationPersistence;
	}

	/**
	 * Sets the category registration persistence.
	 *
	 * @param categoryRegistrationPersistence the category registration persistence
	 */
	public void setCategoryRegistrationPersistence(
		CategoryRegistrationPersistence categoryRegistrationPersistence) {
		this.categoryRegistrationPersistence = categoryRegistrationPersistence;
	}

	/**
	 * Returns the comment registration local service.
	 *
	 * @return the comment registration local service
	 */
	public com.crowd.funding.database.service.CommentRegistrationLocalService getCommentRegistrationLocalService() {
		return commentRegistrationLocalService;
	}

	/**
	 * Sets the comment registration local service.
	 *
	 * @param commentRegistrationLocalService the comment registration local service
	 */
	public void setCommentRegistrationLocalService(
		com.crowd.funding.database.service.CommentRegistrationLocalService commentRegistrationLocalService) {
		this.commentRegistrationLocalService = commentRegistrationLocalService;
	}

	/**
	 * Returns the comment registration remote service.
	 *
	 * @return the comment registration remote service
	 */
	public com.crowd.funding.database.service.CommentRegistrationService getCommentRegistrationService() {
		return commentRegistrationService;
	}

	/**
	 * Sets the comment registration remote service.
	 *
	 * @param commentRegistrationService the comment registration remote service
	 */
	public void setCommentRegistrationService(
		com.crowd.funding.database.service.CommentRegistrationService commentRegistrationService) {
		this.commentRegistrationService = commentRegistrationService;
	}

	/**
	 * Returns the comment registration persistence.
	 *
	 * @return the comment registration persistence
	 */
	public CommentRegistrationPersistence getCommentRegistrationPersistence() {
		return commentRegistrationPersistence;
	}

	/**
	 * Sets the comment registration persistence.
	 *
	 * @param commentRegistrationPersistence the comment registration persistence
	 */
	public void setCommentRegistrationPersistence(
		CommentRegistrationPersistence commentRegistrationPersistence) {
		this.commentRegistrationPersistence = commentRegistrationPersistence;
	}

	/**
	 * Returns the document registration local service.
	 *
	 * @return the document registration local service
	 */
	public com.crowd.funding.database.service.DocumentRegistrationLocalService getDocumentRegistrationLocalService() {
		return documentRegistrationLocalService;
	}

	/**
	 * Sets the document registration local service.
	 *
	 * @param documentRegistrationLocalService the document registration local service
	 */
	public void setDocumentRegistrationLocalService(
		com.crowd.funding.database.service.DocumentRegistrationLocalService documentRegistrationLocalService) {
		this.documentRegistrationLocalService = documentRegistrationLocalService;
	}

	/**
	 * Returns the document registration remote service.
	 *
	 * @return the document registration remote service
	 */
	public com.crowd.funding.database.service.DocumentRegistrationService getDocumentRegistrationService() {
		return documentRegistrationService;
	}

	/**
	 * Sets the document registration remote service.
	 *
	 * @param documentRegistrationService the document registration remote service
	 */
	public void setDocumentRegistrationService(
		com.crowd.funding.database.service.DocumentRegistrationService documentRegistrationService) {
		this.documentRegistrationService = documentRegistrationService;
	}

	/**
	 * Returns the document registration persistence.
	 *
	 * @return the document registration persistence
	 */
	public DocumentRegistrationPersistence getDocumentRegistrationPersistence() {
		return documentRegistrationPersistence;
	}

	/**
	 * Sets the document registration persistence.
	 *
	 * @param documentRegistrationPersistence the document registration persistence
	 */
	public void setDocumentRegistrationPersistence(
		DocumentRegistrationPersistence documentRegistrationPersistence) {
		this.documentRegistrationPersistence = documentRegistrationPersistence;
	}

	/**
	 * Returns the donor registration local service.
	 *
	 * @return the donor registration local service
	 */
	public com.crowd.funding.database.service.DonorRegistrationLocalService getDonorRegistrationLocalService() {
		return donorRegistrationLocalService;
	}

	/**
	 * Sets the donor registration local service.
	 *
	 * @param donorRegistrationLocalService the donor registration local service
	 */
	public void setDonorRegistrationLocalService(
		com.crowd.funding.database.service.DonorRegistrationLocalService donorRegistrationLocalService) {
		this.donorRegistrationLocalService = donorRegistrationLocalService;
	}

	/**
	 * Returns the donor registration remote service.
	 *
	 * @return the donor registration remote service
	 */
	public com.crowd.funding.database.service.DonorRegistrationService getDonorRegistrationService() {
		return donorRegistrationService;
	}

	/**
	 * Sets the donor registration remote service.
	 *
	 * @param donorRegistrationService the donor registration remote service
	 */
	public void setDonorRegistrationService(
		com.crowd.funding.database.service.DonorRegistrationService donorRegistrationService) {
		this.donorRegistrationService = donorRegistrationService;
	}

	/**
	 * Returns the donor registration persistence.
	 *
	 * @return the donor registration persistence
	 */
	public DonorRegistrationPersistence getDonorRegistrationPersistence() {
		return donorRegistrationPersistence;
	}

	/**
	 * Sets the donor registration persistence.
	 *
	 * @param donorRegistrationPersistence the donor registration persistence
	 */
	public void setDonorRegistrationPersistence(
		DonorRegistrationPersistence donorRegistrationPersistence) {
		this.donorRegistrationPersistence = donorRegistrationPersistence;
	}

	/**
	 * Returns the dynamic fees registration local service.
	 *
	 * @return the dynamic fees registration local service
	 */
	public com.crowd.funding.database.service.DynamicFeesRegistrationLocalService getDynamicFeesRegistrationLocalService() {
		return dynamicFeesRegistrationLocalService;
	}

	/**
	 * Sets the dynamic fees registration local service.
	 *
	 * @param dynamicFeesRegistrationLocalService the dynamic fees registration local service
	 */
	public void setDynamicFeesRegistrationLocalService(
		com.crowd.funding.database.service.DynamicFeesRegistrationLocalService dynamicFeesRegistrationLocalService) {
		this.dynamicFeesRegistrationLocalService = dynamicFeesRegistrationLocalService;
	}

	/**
	 * Returns the dynamic fees registration remote service.
	 *
	 * @return the dynamic fees registration remote service
	 */
	public com.crowd.funding.database.service.DynamicFeesRegistrationService getDynamicFeesRegistrationService() {
		return dynamicFeesRegistrationService;
	}

	/**
	 * Sets the dynamic fees registration remote service.
	 *
	 * @param dynamicFeesRegistrationService the dynamic fees registration remote service
	 */
	public void setDynamicFeesRegistrationService(
		com.crowd.funding.database.service.DynamicFeesRegistrationService dynamicFeesRegistrationService) {
		this.dynamicFeesRegistrationService = dynamicFeesRegistrationService;
	}

	/**
	 * Returns the dynamic fees registration persistence.
	 *
	 * @return the dynamic fees registration persistence
	 */
	public DynamicFeesRegistrationPersistence getDynamicFeesRegistrationPersistence() {
		return dynamicFeesRegistrationPersistence;
	}

	/**
	 * Sets the dynamic fees registration persistence.
	 *
	 * @param dynamicFeesRegistrationPersistence the dynamic fees registration persistence
	 */
	public void setDynamicFeesRegistrationPersistence(
		DynamicFeesRegistrationPersistence dynamicFeesRegistrationPersistence) {
		this.dynamicFeesRegistrationPersistence = dynamicFeesRegistrationPersistence;
	}

	/**
	 * Returns the feedback registration local service.
	 *
	 * @return the feedback registration local service
	 */
	public com.crowd.funding.database.service.FeedbackRegistrationLocalService getFeedbackRegistrationLocalService() {
		return feedbackRegistrationLocalService;
	}

	/**
	 * Sets the feedback registration local service.
	 *
	 * @param feedbackRegistrationLocalService the feedback registration local service
	 */
	public void setFeedbackRegistrationLocalService(
		com.crowd.funding.database.service.FeedbackRegistrationLocalService feedbackRegistrationLocalService) {
		this.feedbackRegistrationLocalService = feedbackRegistrationLocalService;
	}

	/**
	 * Returns the feedback registration remote service.
	 *
	 * @return the feedback registration remote service
	 */
	public com.crowd.funding.database.service.FeedbackRegistrationService getFeedbackRegistrationService() {
		return feedbackRegistrationService;
	}

	/**
	 * Sets the feedback registration remote service.
	 *
	 * @param feedbackRegistrationService the feedback registration remote service
	 */
	public void setFeedbackRegistrationService(
		com.crowd.funding.database.service.FeedbackRegistrationService feedbackRegistrationService) {
		this.feedbackRegistrationService = feedbackRegistrationService;
	}

	/**
	 * Returns the feedback registration persistence.
	 *
	 * @return the feedback registration persistence
	 */
	public FeedbackRegistrationPersistence getFeedbackRegistrationPersistence() {
		return feedbackRegistrationPersistence;
	}

	/**
	 * Sets the feedback registration persistence.
	 *
	 * @param feedbackRegistrationPersistence the feedback registration persistence
	 */
	public void setFeedbackRegistrationPersistence(
		FeedbackRegistrationPersistence feedbackRegistrationPersistence) {
		this.feedbackRegistrationPersistence = feedbackRegistrationPersistence;
	}

	/**
	 * Returns the fund account registration local service.
	 *
	 * @return the fund account registration local service
	 */
	public com.crowd.funding.database.service.FundAccountRegistrationLocalService getFundAccountRegistrationLocalService() {
		return fundAccountRegistrationLocalService;
	}

	/**
	 * Sets the fund account registration local service.
	 *
	 * @param fundAccountRegistrationLocalService the fund account registration local service
	 */
	public void setFundAccountRegistrationLocalService(
		com.crowd.funding.database.service.FundAccountRegistrationLocalService fundAccountRegistrationLocalService) {
		this.fundAccountRegistrationLocalService = fundAccountRegistrationLocalService;
	}

	/**
	 * Returns the fund account registration remote service.
	 *
	 * @return the fund account registration remote service
	 */
	public com.crowd.funding.database.service.FundAccountRegistrationService getFundAccountRegistrationService() {
		return fundAccountRegistrationService;
	}

	/**
	 * Sets the fund account registration remote service.
	 *
	 * @param fundAccountRegistrationService the fund account registration remote service
	 */
	public void setFundAccountRegistrationService(
		com.crowd.funding.database.service.FundAccountRegistrationService fundAccountRegistrationService) {
		this.fundAccountRegistrationService = fundAccountRegistrationService;
	}

	/**
	 * Returns the fund account registration persistence.
	 *
	 * @return the fund account registration persistence
	 */
	public FundAccountRegistrationPersistence getFundAccountRegistrationPersistence() {
		return fundAccountRegistrationPersistence;
	}

	/**
	 * Sets the fund account registration persistence.
	 *
	 * @param fundAccountRegistrationPersistence the fund account registration persistence
	 */
	public void setFundAccountRegistrationPersistence(
		FundAccountRegistrationPersistence fundAccountRegistrationPersistence) {
		this.fundAccountRegistrationPersistence = fundAccountRegistrationPersistence;
	}

	/**
	 * Returns the fund registration local service.
	 *
	 * @return the fund registration local service
	 */
	public com.crowd.funding.database.service.FundRegistrationLocalService getFundRegistrationLocalService() {
		return fundRegistrationLocalService;
	}

	/**
	 * Sets the fund registration local service.
	 *
	 * @param fundRegistrationLocalService the fund registration local service
	 */
	public void setFundRegistrationLocalService(
		com.crowd.funding.database.service.FundRegistrationLocalService fundRegistrationLocalService) {
		this.fundRegistrationLocalService = fundRegistrationLocalService;
	}

	/**
	 * Returns the fund registration remote service.
	 *
	 * @return the fund registration remote service
	 */
	public com.crowd.funding.database.service.FundRegistrationService getFundRegistrationService() {
		return fundRegistrationService;
	}

	/**
	 * Sets the fund registration remote service.
	 *
	 * @param fundRegistrationService the fund registration remote service
	 */
	public void setFundRegistrationService(
		com.crowd.funding.database.service.FundRegistrationService fundRegistrationService) {
		this.fundRegistrationService = fundRegistrationService;
	}

	/**
	 * Returns the fund registration persistence.
	 *
	 * @return the fund registration persistence
	 */
	public FundRegistrationPersistence getFundRegistrationPersistence() {
		return fundRegistrationPersistence;
	}

	/**
	 * Sets the fund registration persistence.
	 *
	 * @param fundRegistrationPersistence the fund registration persistence
	 */
	public void setFundRegistrationPersistence(
		FundRegistrationPersistence fundRegistrationPersistence) {
		this.fundRegistrationPersistence = fundRegistrationPersistence;
	}

	/**
	 * Returns the fund release registration local service.
	 *
	 * @return the fund release registration local service
	 */
	public com.crowd.funding.database.service.FundReleaseRegistrationLocalService getFundReleaseRegistrationLocalService() {
		return fundReleaseRegistrationLocalService;
	}

	/**
	 * Sets the fund release registration local service.
	 *
	 * @param fundReleaseRegistrationLocalService the fund release registration local service
	 */
	public void setFundReleaseRegistrationLocalService(
		com.crowd.funding.database.service.FundReleaseRegistrationLocalService fundReleaseRegistrationLocalService) {
		this.fundReleaseRegistrationLocalService = fundReleaseRegistrationLocalService;
	}

	/**
	 * Returns the fund release registration remote service.
	 *
	 * @return the fund release registration remote service
	 */
	public com.crowd.funding.database.service.FundReleaseRegistrationService getFundReleaseRegistrationService() {
		return fundReleaseRegistrationService;
	}

	/**
	 * Sets the fund release registration remote service.
	 *
	 * @param fundReleaseRegistrationService the fund release registration remote service
	 */
	public void setFundReleaseRegistrationService(
		com.crowd.funding.database.service.FundReleaseRegistrationService fundReleaseRegistrationService) {
		this.fundReleaseRegistrationService = fundReleaseRegistrationService;
	}

	/**
	 * Returns the fund release registration persistence.
	 *
	 * @return the fund release registration persistence
	 */
	public FundReleaseRegistrationPersistence getFundReleaseRegistrationPersistence() {
		return fundReleaseRegistrationPersistence;
	}

	/**
	 * Sets the fund release registration persistence.
	 *
	 * @param fundReleaseRegistrationPersistence the fund release registration persistence
	 */
	public void setFundReleaseRegistrationPersistence(
		FundReleaseRegistrationPersistence fundReleaseRegistrationPersistence) {
		this.fundReleaseRegistrationPersistence = fundReleaseRegistrationPersistence;
	}

	/**
	 * Returns the history log registration local service.
	 *
	 * @return the history log registration local service
	 */
	public com.crowd.funding.database.service.HistoryLogRegistrationLocalService getHistoryLogRegistrationLocalService() {
		return historyLogRegistrationLocalService;
	}

	/**
	 * Sets the history log registration local service.
	 *
	 * @param historyLogRegistrationLocalService the history log registration local service
	 */
	public void setHistoryLogRegistrationLocalService(
		com.crowd.funding.database.service.HistoryLogRegistrationLocalService historyLogRegistrationLocalService) {
		this.historyLogRegistrationLocalService = historyLogRegistrationLocalService;
	}

	/**
	 * Returns the history log registration remote service.
	 *
	 * @return the history log registration remote service
	 */
	public com.crowd.funding.database.service.HistoryLogRegistrationService getHistoryLogRegistrationService() {
		return historyLogRegistrationService;
	}

	/**
	 * Sets the history log registration remote service.
	 *
	 * @param historyLogRegistrationService the history log registration remote service
	 */
	public void setHistoryLogRegistrationService(
		com.crowd.funding.database.service.HistoryLogRegistrationService historyLogRegistrationService) {
		this.historyLogRegistrationService = historyLogRegistrationService;
	}

	/**
	 * Returns the history log registration persistence.
	 *
	 * @return the history log registration persistence
	 */
	public HistoryLogRegistrationPersistence getHistoryLogRegistrationPersistence() {
		return historyLogRegistrationPersistence;
	}

	/**
	 * Sets the history log registration persistence.
	 *
	 * @param historyLogRegistrationPersistence the history log registration persistence
	 */
	public void setHistoryLogRegistrationPersistence(
		HistoryLogRegistrationPersistence historyLogRegistrationPersistence) {
		this.historyLogRegistrationPersistence = historyLogRegistrationPersistence;
	}

	/**
	 * Returns the image registration local service.
	 *
	 * @return the image registration local service
	 */
	public com.crowd.funding.database.service.ImageRegistrationLocalService getImageRegistrationLocalService() {
		return imageRegistrationLocalService;
	}

	/**
	 * Sets the image registration local service.
	 *
	 * @param imageRegistrationLocalService the image registration local service
	 */
	public void setImageRegistrationLocalService(
		com.crowd.funding.database.service.ImageRegistrationLocalService imageRegistrationLocalService) {
		this.imageRegistrationLocalService = imageRegistrationLocalService;
	}

	/**
	 * Returns the image registration remote service.
	 *
	 * @return the image registration remote service
	 */
	public com.crowd.funding.database.service.ImageRegistrationService getImageRegistrationService() {
		return imageRegistrationService;
	}

	/**
	 * Sets the image registration remote service.
	 *
	 * @param imageRegistrationService the image registration remote service
	 */
	public void setImageRegistrationService(
		com.crowd.funding.database.service.ImageRegistrationService imageRegistrationService) {
		this.imageRegistrationService = imageRegistrationService;
	}

	/**
	 * Returns the image registration persistence.
	 *
	 * @return the image registration persistence
	 */
	public ImageRegistrationPersistence getImageRegistrationPersistence() {
		return imageRegistrationPersistence;
	}

	/**
	 * Sets the image registration persistence.
	 *
	 * @param imageRegistrationPersistence the image registration persistence
	 */
	public void setImageRegistrationPersistence(
		ImageRegistrationPersistence imageRegistrationPersistence) {
		this.imageRegistrationPersistence = imageRegistrationPersistence;
	}

	/**
	 * Returns the news letter registration local service.
	 *
	 * @return the news letter registration local service
	 */
	public com.crowd.funding.database.service.NewsLetterRegistrationLocalService getNewsLetterRegistrationLocalService() {
		return newsLetterRegistrationLocalService;
	}

	/**
	 * Sets the news letter registration local service.
	 *
	 * @param newsLetterRegistrationLocalService the news letter registration local service
	 */
	public void setNewsLetterRegistrationLocalService(
		com.crowd.funding.database.service.NewsLetterRegistrationLocalService newsLetterRegistrationLocalService) {
		this.newsLetterRegistrationLocalService = newsLetterRegistrationLocalService;
	}

	/**
	 * Returns the news letter registration remote service.
	 *
	 * @return the news letter registration remote service
	 */
	public com.crowd.funding.database.service.NewsLetterRegistrationService getNewsLetterRegistrationService() {
		return newsLetterRegistrationService;
	}

	/**
	 * Sets the news letter registration remote service.
	 *
	 * @param newsLetterRegistrationService the news letter registration remote service
	 */
	public void setNewsLetterRegistrationService(
		com.crowd.funding.database.service.NewsLetterRegistrationService newsLetterRegistrationService) {
		this.newsLetterRegistrationService = newsLetterRegistrationService;
	}

	/**
	 * Returns the news letter registration persistence.
	 *
	 * @return the news letter registration persistence
	 */
	public NewsLetterRegistrationPersistence getNewsLetterRegistrationPersistence() {
		return newsLetterRegistrationPersistence;
	}

	/**
	 * Sets the news letter registration persistence.
	 *
	 * @param newsLetterRegistrationPersistence the news letter registration persistence
	 */
	public void setNewsLetterRegistrationPersistence(
		NewsLetterRegistrationPersistence newsLetterRegistrationPersistence) {
		this.newsLetterRegistrationPersistence = newsLetterRegistrationPersistence;
	}

	/**
	 * Returns the position registration local service.
	 *
	 * @return the position registration local service
	 */
	public com.crowd.funding.database.service.PositionRegistrationLocalService getPositionRegistrationLocalService() {
		return positionRegistrationLocalService;
	}

	/**
	 * Sets the position registration local service.
	 *
	 * @param positionRegistrationLocalService the position registration local service
	 */
	public void setPositionRegistrationLocalService(
		com.crowd.funding.database.service.PositionRegistrationLocalService positionRegistrationLocalService) {
		this.positionRegistrationLocalService = positionRegistrationLocalService;
	}

	/**
	 * Returns the position registration remote service.
	 *
	 * @return the position registration remote service
	 */
	public com.crowd.funding.database.service.PositionRegistrationService getPositionRegistrationService() {
		return positionRegistrationService;
	}

	/**
	 * Sets the position registration remote service.
	 *
	 * @param positionRegistrationService the position registration remote service
	 */
	public void setPositionRegistrationService(
		com.crowd.funding.database.service.PositionRegistrationService positionRegistrationService) {
		this.positionRegistrationService = positionRegistrationService;
	}

	/**
	 * Returns the position registration persistence.
	 *
	 * @return the position registration persistence
	 */
	public PositionRegistrationPersistence getPositionRegistrationPersistence() {
		return positionRegistrationPersistence;
	}

	/**
	 * Sets the position registration persistence.
	 *
	 * @param positionRegistrationPersistence the position registration persistence
	 */
	public void setPositionRegistrationPersistence(
		PositionRegistrationPersistence positionRegistrationPersistence) {
		this.positionRegistrationPersistence = positionRegistrationPersistence;
	}

	/**
	 * Returns the project acknowledgement registration local service.
	 *
	 * @return the project acknowledgement registration local service
	 */
	public com.crowd.funding.database.service.ProjectAcknowledgementRegistrationLocalService getProjectAcknowledgementRegistrationLocalService() {
		return projectAcknowledgementRegistrationLocalService;
	}

	/**
	 * Sets the project acknowledgement registration local service.
	 *
	 * @param projectAcknowledgementRegistrationLocalService the project acknowledgement registration local service
	 */
	public void setProjectAcknowledgementRegistrationLocalService(
		com.crowd.funding.database.service.ProjectAcknowledgementRegistrationLocalService projectAcknowledgementRegistrationLocalService) {
		this.projectAcknowledgementRegistrationLocalService = projectAcknowledgementRegistrationLocalService;
	}

	/**
	 * Returns the project acknowledgement registration remote service.
	 *
	 * @return the project acknowledgement registration remote service
	 */
	public com.crowd.funding.database.service.ProjectAcknowledgementRegistrationService getProjectAcknowledgementRegistrationService() {
		return projectAcknowledgementRegistrationService;
	}

	/**
	 * Sets the project acknowledgement registration remote service.
	 *
	 * @param projectAcknowledgementRegistrationService the project acknowledgement registration remote service
	 */
	public void setProjectAcknowledgementRegistrationService(
		com.crowd.funding.database.service.ProjectAcknowledgementRegistrationService projectAcknowledgementRegistrationService) {
		this.projectAcknowledgementRegistrationService = projectAcknowledgementRegistrationService;
	}

	/**
	 * Returns the project acknowledgement registration persistence.
	 *
	 * @return the project acknowledgement registration persistence
	 */
	public ProjectAcknowledgementRegistrationPersistence getProjectAcknowledgementRegistrationPersistence() {
		return projectAcknowledgementRegistrationPersistence;
	}

	/**
	 * Sets the project acknowledgement registration persistence.
	 *
	 * @param projectAcknowledgementRegistrationPersistence the project acknowledgement registration persistence
	 */
	public void setProjectAcknowledgementRegistrationPersistence(
		ProjectAcknowledgementRegistrationPersistence projectAcknowledgementRegistrationPersistence) {
		this.projectAcknowledgementRegistrationPersistence = projectAcknowledgementRegistrationPersistence;
	}

	/**
	 * Returns the project extention registration local service.
	 *
	 * @return the project extention registration local service
	 */
	public com.crowd.funding.database.service.ProjectExtentionRegistrationLocalService getProjectExtentionRegistrationLocalService() {
		return projectExtentionRegistrationLocalService;
	}

	/**
	 * Sets the project extention registration local service.
	 *
	 * @param projectExtentionRegistrationLocalService the project extention registration local service
	 */
	public void setProjectExtentionRegistrationLocalService(
		com.crowd.funding.database.service.ProjectExtentionRegistrationLocalService projectExtentionRegistrationLocalService) {
		this.projectExtentionRegistrationLocalService = projectExtentionRegistrationLocalService;
	}

	/**
	 * Returns the project extention registration remote service.
	 *
	 * @return the project extention registration remote service
	 */
	public com.crowd.funding.database.service.ProjectExtentionRegistrationService getProjectExtentionRegistrationService() {
		return projectExtentionRegistrationService;
	}

	/**
	 * Sets the project extention registration remote service.
	 *
	 * @param projectExtentionRegistrationService the project extention registration remote service
	 */
	public void setProjectExtentionRegistrationService(
		com.crowd.funding.database.service.ProjectExtentionRegistrationService projectExtentionRegistrationService) {
		this.projectExtentionRegistrationService = projectExtentionRegistrationService;
	}

	/**
	 * Returns the project extention registration persistence.
	 *
	 * @return the project extention registration persistence
	 */
	public ProjectExtentionRegistrationPersistence getProjectExtentionRegistrationPersistence() {
		return projectExtentionRegistrationPersistence;
	}

	/**
	 * Sets the project extention registration persistence.
	 *
	 * @param projectExtentionRegistrationPersistence the project extention registration persistence
	 */
	public void setProjectExtentionRegistrationPersistence(
		ProjectExtentionRegistrationPersistence projectExtentionRegistrationPersistence) {
		this.projectExtentionRegistrationPersistence = projectExtentionRegistrationPersistence;
	}

	/**
	 * Returns the project fees registration local service.
	 *
	 * @return the project fees registration local service
	 */
	public com.crowd.funding.database.service.ProjectFeesRegistrationLocalService getProjectFeesRegistrationLocalService() {
		return projectFeesRegistrationLocalService;
	}

	/**
	 * Sets the project fees registration local service.
	 *
	 * @param projectFeesRegistrationLocalService the project fees registration local service
	 */
	public void setProjectFeesRegistrationLocalService(
		com.crowd.funding.database.service.ProjectFeesRegistrationLocalService projectFeesRegistrationLocalService) {
		this.projectFeesRegistrationLocalService = projectFeesRegistrationLocalService;
	}

	/**
	 * Returns the project fees registration remote service.
	 *
	 * @return the project fees registration remote service
	 */
	public com.crowd.funding.database.service.ProjectFeesRegistrationService getProjectFeesRegistrationService() {
		return projectFeesRegistrationService;
	}

	/**
	 * Sets the project fees registration remote service.
	 *
	 * @param projectFeesRegistrationService the project fees registration remote service
	 */
	public void setProjectFeesRegistrationService(
		com.crowd.funding.database.service.ProjectFeesRegistrationService projectFeesRegistrationService) {
		this.projectFeesRegistrationService = projectFeesRegistrationService;
	}

	/**
	 * Returns the project fees registration persistence.
	 *
	 * @return the project fees registration persistence
	 */
	public ProjectFeesRegistrationPersistence getProjectFeesRegistrationPersistence() {
		return projectFeesRegistrationPersistence;
	}

	/**
	 * Sets the project fees registration persistence.
	 *
	 * @param projectFeesRegistrationPersistence the project fees registration persistence
	 */
	public void setProjectFeesRegistrationPersistence(
		ProjectFeesRegistrationPersistence projectFeesRegistrationPersistence) {
		this.projectFeesRegistrationPersistence = projectFeesRegistrationPersistence;
	}

	/**
	 * Returns the project follower registration local service.
	 *
	 * @return the project follower registration local service
	 */
	public com.crowd.funding.database.service.ProjectFollowerRegistrationLocalService getProjectFollowerRegistrationLocalService() {
		return projectFollowerRegistrationLocalService;
	}

	/**
	 * Sets the project follower registration local service.
	 *
	 * @param projectFollowerRegistrationLocalService the project follower registration local service
	 */
	public void setProjectFollowerRegistrationLocalService(
		com.crowd.funding.database.service.ProjectFollowerRegistrationLocalService projectFollowerRegistrationLocalService) {
		this.projectFollowerRegistrationLocalService = projectFollowerRegistrationLocalService;
	}

	/**
	 * Returns the project follower registration remote service.
	 *
	 * @return the project follower registration remote service
	 */
	public com.crowd.funding.database.service.ProjectFollowerRegistrationService getProjectFollowerRegistrationService() {
		return projectFollowerRegistrationService;
	}

	/**
	 * Sets the project follower registration remote service.
	 *
	 * @param projectFollowerRegistrationService the project follower registration remote service
	 */
	public void setProjectFollowerRegistrationService(
		com.crowd.funding.database.service.ProjectFollowerRegistrationService projectFollowerRegistrationService) {
		this.projectFollowerRegistrationService = projectFollowerRegistrationService;
	}

	/**
	 * Returns the project follower registration persistence.
	 *
	 * @return the project follower registration persistence
	 */
	public ProjectFollowerRegistrationPersistence getProjectFollowerRegistrationPersistence() {
		return projectFollowerRegistrationPersistence;
	}

	/**
	 * Sets the project follower registration persistence.
	 *
	 * @param projectFollowerRegistrationPersistence the project follower registration persistence
	 */
	public void setProjectFollowerRegistrationPersistence(
		ProjectFollowerRegistrationPersistence projectFollowerRegistrationPersistence) {
		this.projectFollowerRegistrationPersistence = projectFollowerRegistrationPersistence;
	}

	/**
	 * Returns the project priority registration local service.
	 *
	 * @return the project priority registration local service
	 */
	public com.crowd.funding.database.service.ProjectPriorityRegistrationLocalService getProjectPriorityRegistrationLocalService() {
		return projectPriorityRegistrationLocalService;
	}

	/**
	 * Sets the project priority registration local service.
	 *
	 * @param projectPriorityRegistrationLocalService the project priority registration local service
	 */
	public void setProjectPriorityRegistrationLocalService(
		com.crowd.funding.database.service.ProjectPriorityRegistrationLocalService projectPriorityRegistrationLocalService) {
		this.projectPriorityRegistrationLocalService = projectPriorityRegistrationLocalService;
	}

	/**
	 * Returns the project priority registration remote service.
	 *
	 * @return the project priority registration remote service
	 */
	public com.crowd.funding.database.service.ProjectPriorityRegistrationService getProjectPriorityRegistrationService() {
		return projectPriorityRegistrationService;
	}

	/**
	 * Sets the project priority registration remote service.
	 *
	 * @param projectPriorityRegistrationService the project priority registration remote service
	 */
	public void setProjectPriorityRegistrationService(
		com.crowd.funding.database.service.ProjectPriorityRegistrationService projectPriorityRegistrationService) {
		this.projectPriorityRegistrationService = projectPriorityRegistrationService;
	}

	/**
	 * Returns the project priority registration persistence.
	 *
	 * @return the project priority registration persistence
	 */
	public ProjectPriorityRegistrationPersistence getProjectPriorityRegistrationPersistence() {
		return projectPriorityRegistrationPersistence;
	}

	/**
	 * Sets the project priority registration persistence.
	 *
	 * @param projectPriorityRegistrationPersistence the project priority registration persistence
	 */
	public void setProjectPriorityRegistrationPersistence(
		ProjectPriorityRegistrationPersistence projectPriorityRegistrationPersistence) {
		this.projectPriorityRegistrationPersistence = projectPriorityRegistrationPersistence;
	}

	/**
	 * Returns the project registration local service.
	 *
	 * @return the project registration local service
	 */
	public com.crowd.funding.database.service.ProjectRegistrationLocalService getProjectRegistrationLocalService() {
		return projectRegistrationLocalService;
	}

	/**
	 * Sets the project registration local service.
	 *
	 * @param projectRegistrationLocalService the project registration local service
	 */
	public void setProjectRegistrationLocalService(
		com.crowd.funding.database.service.ProjectRegistrationLocalService projectRegistrationLocalService) {
		this.projectRegistrationLocalService = projectRegistrationLocalService;
	}

	/**
	 * Returns the project registration remote service.
	 *
	 * @return the project registration remote service
	 */
	public com.crowd.funding.database.service.ProjectRegistrationService getProjectRegistrationService() {
		return projectRegistrationService;
	}

	/**
	 * Sets the project registration remote service.
	 *
	 * @param projectRegistrationService the project registration remote service
	 */
	public void setProjectRegistrationService(
		com.crowd.funding.database.service.ProjectRegistrationService projectRegistrationService) {
		this.projectRegistrationService = projectRegistrationService;
	}

	/**
	 * Returns the project registration persistence.
	 *
	 * @return the project registration persistence
	 */
	public ProjectRegistrationPersistence getProjectRegistrationPersistence() {
		return projectRegistrationPersistence;
	}

	/**
	 * Sets the project registration persistence.
	 *
	 * @param projectRegistrationPersistence the project registration persistence
	 */
	public void setProjectRegistrationPersistence(
		ProjectRegistrationPersistence projectRegistrationPersistence) {
		this.projectRegistrationPersistence = projectRegistrationPersistence;
	}

	/**
	 * Returns the project registration finder.
	 *
	 * @return the project registration finder
	 */
	public ProjectRegistrationFinder getProjectRegistrationFinder() {
		return projectRegistrationFinder;
	}

	/**
	 * Sets the project registration finder.
	 *
	 * @param projectRegistrationFinder the project registration finder
	 */
	public void setProjectRegistrationFinder(
		ProjectRegistrationFinder projectRegistrationFinder) {
		this.projectRegistrationFinder = projectRegistrationFinder;
	}

	/**
	 * Returns the project update registration local service.
	 *
	 * @return the project update registration local service
	 */
	public com.crowd.funding.database.service.ProjectUpdateRegistrationLocalService getProjectUpdateRegistrationLocalService() {
		return projectUpdateRegistrationLocalService;
	}

	/**
	 * Sets the project update registration local service.
	 *
	 * @param projectUpdateRegistrationLocalService the project update registration local service
	 */
	public void setProjectUpdateRegistrationLocalService(
		com.crowd.funding.database.service.ProjectUpdateRegistrationLocalService projectUpdateRegistrationLocalService) {
		this.projectUpdateRegistrationLocalService = projectUpdateRegistrationLocalService;
	}

	/**
	 * Returns the project update registration remote service.
	 *
	 * @return the project update registration remote service
	 */
	public com.crowd.funding.database.service.ProjectUpdateRegistrationService getProjectUpdateRegistrationService() {
		return projectUpdateRegistrationService;
	}

	/**
	 * Sets the project update registration remote service.
	 *
	 * @param projectUpdateRegistrationService the project update registration remote service
	 */
	public void setProjectUpdateRegistrationService(
		com.crowd.funding.database.service.ProjectUpdateRegistrationService projectUpdateRegistrationService) {
		this.projectUpdateRegistrationService = projectUpdateRegistrationService;
	}

	/**
	 * Returns the project update registration persistence.
	 *
	 * @return the project update registration persistence
	 */
	public ProjectUpdateRegistrationPersistence getProjectUpdateRegistrationPersistence() {
		return projectUpdateRegistrationPersistence;
	}

	/**
	 * Sets the project update registration persistence.
	 *
	 * @param projectUpdateRegistrationPersistence the project update registration persistence
	 */
	public void setProjectUpdateRegistrationPersistence(
		ProjectUpdateRegistrationPersistence projectUpdateRegistrationPersistence) {
		this.projectUpdateRegistrationPersistence = projectUpdateRegistrationPersistence;
	}

	/**
	 * Returns the question registration local service.
	 *
	 * @return the question registration local service
	 */
	public com.crowd.funding.database.service.QuestionRegistrationLocalService getQuestionRegistrationLocalService() {
		return questionRegistrationLocalService;
	}

	/**
	 * Sets the question registration local service.
	 *
	 * @param questionRegistrationLocalService the question registration local service
	 */
	public void setQuestionRegistrationLocalService(
		com.crowd.funding.database.service.QuestionRegistrationLocalService questionRegistrationLocalService) {
		this.questionRegistrationLocalService = questionRegistrationLocalService;
	}

	/**
	 * Returns the question registration remote service.
	 *
	 * @return the question registration remote service
	 */
	public com.crowd.funding.database.service.QuestionRegistrationService getQuestionRegistrationService() {
		return questionRegistrationService;
	}

	/**
	 * Sets the question registration remote service.
	 *
	 * @param questionRegistrationService the question registration remote service
	 */
	public void setQuestionRegistrationService(
		com.crowd.funding.database.service.QuestionRegistrationService questionRegistrationService) {
		this.questionRegistrationService = questionRegistrationService;
	}

	/**
	 * Returns the question registration persistence.
	 *
	 * @return the question registration persistence
	 */
	public QuestionRegistrationPersistence getQuestionRegistrationPersistence() {
		return questionRegistrationPersistence;
	}

	/**
	 * Sets the question registration persistence.
	 *
	 * @param questionRegistrationPersistence the question registration persistence
	 */
	public void setQuestionRegistrationPersistence(
		QuestionRegistrationPersistence questionRegistrationPersistence) {
		this.questionRegistrationPersistence = questionRegistrationPersistence;
	}

	/**
	 * Returns the subscription registration local service.
	 *
	 * @return the subscription registration local service
	 */
	public com.crowd.funding.database.service.SubscriptionRegistrationLocalService getSubscriptionRegistrationLocalService() {
		return subscriptionRegistrationLocalService;
	}

	/**
	 * Sets the subscription registration local service.
	 *
	 * @param subscriptionRegistrationLocalService the subscription registration local service
	 */
	public void setSubscriptionRegistrationLocalService(
		com.crowd.funding.database.service.SubscriptionRegistrationLocalService subscriptionRegistrationLocalService) {
		this.subscriptionRegistrationLocalService = subscriptionRegistrationLocalService;
	}

	/**
	 * Returns the subscription registration remote service.
	 *
	 * @return the subscription registration remote service
	 */
	public com.crowd.funding.database.service.SubscriptionRegistrationService getSubscriptionRegistrationService() {
		return subscriptionRegistrationService;
	}

	/**
	 * Sets the subscription registration remote service.
	 *
	 * @param subscriptionRegistrationService the subscription registration remote service
	 */
	public void setSubscriptionRegistrationService(
		com.crowd.funding.database.service.SubscriptionRegistrationService subscriptionRegistrationService) {
		this.subscriptionRegistrationService = subscriptionRegistrationService;
	}

	/**
	 * Returns the subscription registration persistence.
	 *
	 * @return the subscription registration persistence
	 */
	public SubscriptionRegistrationPersistence getSubscriptionRegistrationPersistence() {
		return subscriptionRegistrationPersistence;
	}

	/**
	 * Sets the subscription registration persistence.
	 *
	 * @param subscriptionRegistrationPersistence the subscription registration persistence
	 */
	public void setSubscriptionRegistrationPersistence(
		SubscriptionRegistrationPersistence subscriptionRegistrationPersistence) {
		this.subscriptionRegistrationPersistence = subscriptionRegistrationPersistence;
	}

	/**
	 * Returns the update requester registration local service.
	 *
	 * @return the update requester registration local service
	 */
	public com.crowd.funding.database.service.UpdateRequesterRegistrationLocalService getUpdateRequesterRegistrationLocalService() {
		return updateRequesterRegistrationLocalService;
	}

	/**
	 * Sets the update requester registration local service.
	 *
	 * @param updateRequesterRegistrationLocalService the update requester registration local service
	 */
	public void setUpdateRequesterRegistrationLocalService(
		com.crowd.funding.database.service.UpdateRequesterRegistrationLocalService updateRequesterRegistrationLocalService) {
		this.updateRequesterRegistrationLocalService = updateRequesterRegistrationLocalService;
	}

	/**
	 * Returns the update requester registration remote service.
	 *
	 * @return the update requester registration remote service
	 */
	public com.crowd.funding.database.service.UpdateRequesterRegistrationService getUpdateRequesterRegistrationService() {
		return updateRequesterRegistrationService;
	}

	/**
	 * Sets the update requester registration remote service.
	 *
	 * @param updateRequesterRegistrationService the update requester registration remote service
	 */
	public void setUpdateRequesterRegistrationService(
		com.crowd.funding.database.service.UpdateRequesterRegistrationService updateRequesterRegistrationService) {
		this.updateRequesterRegistrationService = updateRequesterRegistrationService;
	}

	/**
	 * Returns the update requester registration persistence.
	 *
	 * @return the update requester registration persistence
	 */
	public UpdateRequesterRegistrationPersistence getUpdateRequesterRegistrationPersistence() {
		return updateRequesterRegistrationPersistence;
	}

	/**
	 * Sets the update requester registration persistence.
	 *
	 * @param updateRequesterRegistrationPersistence the update requester registration persistence
	 */
	public void setUpdateRequesterRegistrationPersistence(
		UpdateRequesterRegistrationPersistence updateRequesterRegistrationPersistence) {
		this.updateRequesterRegistrationPersistence = updateRequesterRegistrationPersistence;
	}

	/**
	 * Returns the user follow registration local service.
	 *
	 * @return the user follow registration local service
	 */
	public com.crowd.funding.database.service.UserFollowRegistrationLocalService getUserFollowRegistrationLocalService() {
		return userFollowRegistrationLocalService;
	}

	/**
	 * Sets the user follow registration local service.
	 *
	 * @param userFollowRegistrationLocalService the user follow registration local service
	 */
	public void setUserFollowRegistrationLocalService(
		com.crowd.funding.database.service.UserFollowRegistrationLocalService userFollowRegistrationLocalService) {
		this.userFollowRegistrationLocalService = userFollowRegistrationLocalService;
	}

	/**
	 * Returns the user follow registration remote service.
	 *
	 * @return the user follow registration remote service
	 */
	public UserFollowRegistrationService getUserFollowRegistrationService() {
		return userFollowRegistrationService;
	}

	/**
	 * Sets the user follow registration remote service.
	 *
	 * @param userFollowRegistrationService the user follow registration remote service
	 */
	public void setUserFollowRegistrationService(
		UserFollowRegistrationService userFollowRegistrationService) {
		this.userFollowRegistrationService = userFollowRegistrationService;
	}

	/**
	 * Returns the user follow registration persistence.
	 *
	 * @return the user follow registration persistence
	 */
	public UserFollowRegistrationPersistence getUserFollowRegistrationPersistence() {
		return userFollowRegistrationPersistence;
	}

	/**
	 * Sets the user follow registration persistence.
	 *
	 * @param userFollowRegistrationPersistence the user follow registration persistence
	 */
	public void setUserFollowRegistrationPersistence(
		UserFollowRegistrationPersistence userFollowRegistrationPersistence) {
		this.userFollowRegistrationPersistence = userFollowRegistrationPersistence;
	}

	/**
	 * Returns the user otp registration local service.
	 *
	 * @return the user otp registration local service
	 */
	public com.crowd.funding.database.service.UserOTPRegistrationLocalService getUserOTPRegistrationLocalService() {
		return userOTPRegistrationLocalService;
	}

	/**
	 * Sets the user otp registration local service.
	 *
	 * @param userOTPRegistrationLocalService the user otp registration local service
	 */
	public void setUserOTPRegistrationLocalService(
		com.crowd.funding.database.service.UserOTPRegistrationLocalService userOTPRegistrationLocalService) {
		this.userOTPRegistrationLocalService = userOTPRegistrationLocalService;
	}

	/**
	 * Returns the user otp registration remote service.
	 *
	 * @return the user otp registration remote service
	 */
	public com.crowd.funding.database.service.UserOTPRegistrationService getUserOTPRegistrationService() {
		return userOTPRegistrationService;
	}

	/**
	 * Sets the user otp registration remote service.
	 *
	 * @param userOTPRegistrationService the user otp registration remote service
	 */
	public void setUserOTPRegistrationService(
		com.crowd.funding.database.service.UserOTPRegistrationService userOTPRegistrationService) {
		this.userOTPRegistrationService = userOTPRegistrationService;
	}

	/**
	 * Returns the user otp registration persistence.
	 *
	 * @return the user otp registration persistence
	 */
	public UserOTPRegistrationPersistence getUserOTPRegistrationPersistence() {
		return userOTPRegistrationPersistence;
	}

	/**
	 * Sets the user otp registration persistence.
	 *
	 * @param userOTPRegistrationPersistence the user otp registration persistence
	 */
	public void setUserOTPRegistrationPersistence(
		UserOTPRegistrationPersistence userOTPRegistrationPersistence) {
		this.userOTPRegistrationPersistence = userOTPRegistrationPersistence;
	}

	/**
	 * Returns the user registration local service.
	 *
	 * @return the user registration local service
	 */
	public com.crowd.funding.database.service.UserRegistrationLocalService getUserRegistrationLocalService() {
		return userRegistrationLocalService;
	}

	/**
	 * Sets the user registration local service.
	 *
	 * @param userRegistrationLocalService the user registration local service
	 */
	public void setUserRegistrationLocalService(
		com.crowd.funding.database.service.UserRegistrationLocalService userRegistrationLocalService) {
		this.userRegistrationLocalService = userRegistrationLocalService;
	}

	/**
	 * Returns the user registration remote service.
	 *
	 * @return the user registration remote service
	 */
	public com.crowd.funding.database.service.UserRegistrationService getUserRegistrationService() {
		return userRegistrationService;
	}

	/**
	 * Sets the user registration remote service.
	 *
	 * @param userRegistrationService the user registration remote service
	 */
	public void setUserRegistrationService(
		com.crowd.funding.database.service.UserRegistrationService userRegistrationService) {
		this.userRegistrationService = userRegistrationService;
	}

	/**
	 * Returns the user registration persistence.
	 *
	 * @return the user registration persistence
	 */
	public UserRegistrationPersistence getUserRegistrationPersistence() {
		return userRegistrationPersistence;
	}

	/**
	 * Sets the user registration persistence.
	 *
	 * @param userRegistrationPersistence the user registration persistence
	 */
	public void setUserRegistrationPersistence(
		UserRegistrationPersistence userRegistrationPersistence) {
		this.userRegistrationPersistence = userRegistrationPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UserFollowRegistrationService.class.getName();
	}

	protected Class<?> getModelClass() {
		return UserFollowRegistration.class;
	}

	protected String getModelClassName() {
		return UserFollowRegistration.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = userFollowRegistrationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.crowd.funding.database.service.BenificiaryRegistrationLocalService.class)
	protected com.crowd.funding.database.service.BenificiaryRegistrationLocalService benificiaryRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.BenificiaryRegistrationService.class)
	protected com.crowd.funding.database.service.BenificiaryRegistrationService benificiaryRegistrationService;
	@BeanReference(type = BenificiaryRegistrationPersistence.class)
	protected BenificiaryRegistrationPersistence benificiaryRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.CandidateRegistrationLocalService.class)
	protected com.crowd.funding.database.service.CandidateRegistrationLocalService candidateRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.CandidateRegistrationService.class)
	protected com.crowd.funding.database.service.CandidateRegistrationService candidateRegistrationService;
	@BeanReference(type = CandidateRegistrationPersistence.class)
	protected CandidateRegistrationPersistence candidateRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.CategoryRegistrationLocalService.class)
	protected com.crowd.funding.database.service.CategoryRegistrationLocalService categoryRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.CategoryRegistrationService.class)
	protected com.crowd.funding.database.service.CategoryRegistrationService categoryRegistrationService;
	@BeanReference(type = CategoryRegistrationPersistence.class)
	protected CategoryRegistrationPersistence categoryRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.CommentRegistrationLocalService.class)
	protected com.crowd.funding.database.service.CommentRegistrationLocalService commentRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.CommentRegistrationService.class)
	protected com.crowd.funding.database.service.CommentRegistrationService commentRegistrationService;
	@BeanReference(type = CommentRegistrationPersistence.class)
	protected CommentRegistrationPersistence commentRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.DocumentRegistrationLocalService.class)
	protected com.crowd.funding.database.service.DocumentRegistrationLocalService documentRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.DocumentRegistrationService.class)
	protected com.crowd.funding.database.service.DocumentRegistrationService documentRegistrationService;
	@BeanReference(type = DocumentRegistrationPersistence.class)
	protected DocumentRegistrationPersistence documentRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.DonorRegistrationLocalService.class)
	protected com.crowd.funding.database.service.DonorRegistrationLocalService donorRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.DonorRegistrationService.class)
	protected com.crowd.funding.database.service.DonorRegistrationService donorRegistrationService;
	@BeanReference(type = DonorRegistrationPersistence.class)
	protected DonorRegistrationPersistence donorRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.DynamicFeesRegistrationLocalService.class)
	protected com.crowd.funding.database.service.DynamicFeesRegistrationLocalService dynamicFeesRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.DynamicFeesRegistrationService.class)
	protected com.crowd.funding.database.service.DynamicFeesRegistrationService dynamicFeesRegistrationService;
	@BeanReference(type = DynamicFeesRegistrationPersistence.class)
	protected DynamicFeesRegistrationPersistence dynamicFeesRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.FeedbackRegistrationLocalService.class)
	protected com.crowd.funding.database.service.FeedbackRegistrationLocalService feedbackRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.FeedbackRegistrationService.class)
	protected com.crowd.funding.database.service.FeedbackRegistrationService feedbackRegistrationService;
	@BeanReference(type = FeedbackRegistrationPersistence.class)
	protected FeedbackRegistrationPersistence feedbackRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.FundAccountRegistrationLocalService.class)
	protected com.crowd.funding.database.service.FundAccountRegistrationLocalService fundAccountRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.FundAccountRegistrationService.class)
	protected com.crowd.funding.database.service.FundAccountRegistrationService fundAccountRegistrationService;
	@BeanReference(type = FundAccountRegistrationPersistence.class)
	protected FundAccountRegistrationPersistence fundAccountRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.FundRegistrationLocalService.class)
	protected com.crowd.funding.database.service.FundRegistrationLocalService fundRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.FundRegistrationService.class)
	protected com.crowd.funding.database.service.FundRegistrationService fundRegistrationService;
	@BeanReference(type = FundRegistrationPersistence.class)
	protected FundRegistrationPersistence fundRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.FundReleaseRegistrationLocalService.class)
	protected com.crowd.funding.database.service.FundReleaseRegistrationLocalService fundReleaseRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.FundReleaseRegistrationService.class)
	protected com.crowd.funding.database.service.FundReleaseRegistrationService fundReleaseRegistrationService;
	@BeanReference(type = FundReleaseRegistrationPersistence.class)
	protected FundReleaseRegistrationPersistence fundReleaseRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.HistoryLogRegistrationLocalService.class)
	protected com.crowd.funding.database.service.HistoryLogRegistrationLocalService historyLogRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.HistoryLogRegistrationService.class)
	protected com.crowd.funding.database.service.HistoryLogRegistrationService historyLogRegistrationService;
	@BeanReference(type = HistoryLogRegistrationPersistence.class)
	protected HistoryLogRegistrationPersistence historyLogRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.ImageRegistrationLocalService.class)
	protected com.crowd.funding.database.service.ImageRegistrationLocalService imageRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.ImageRegistrationService.class)
	protected com.crowd.funding.database.service.ImageRegistrationService imageRegistrationService;
	@BeanReference(type = ImageRegistrationPersistence.class)
	protected ImageRegistrationPersistence imageRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.NewsLetterRegistrationLocalService.class)
	protected com.crowd.funding.database.service.NewsLetterRegistrationLocalService newsLetterRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.NewsLetterRegistrationService.class)
	protected com.crowd.funding.database.service.NewsLetterRegistrationService newsLetterRegistrationService;
	@BeanReference(type = NewsLetterRegistrationPersistence.class)
	protected NewsLetterRegistrationPersistence newsLetterRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.PositionRegistrationLocalService.class)
	protected com.crowd.funding.database.service.PositionRegistrationLocalService positionRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.PositionRegistrationService.class)
	protected com.crowd.funding.database.service.PositionRegistrationService positionRegistrationService;
	@BeanReference(type = PositionRegistrationPersistence.class)
	protected PositionRegistrationPersistence positionRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.ProjectAcknowledgementRegistrationLocalService.class)
	protected com.crowd.funding.database.service.ProjectAcknowledgementRegistrationLocalService projectAcknowledgementRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.ProjectAcknowledgementRegistrationService.class)
	protected com.crowd.funding.database.service.ProjectAcknowledgementRegistrationService projectAcknowledgementRegistrationService;
	@BeanReference(type = ProjectAcknowledgementRegistrationPersistence.class)
	protected ProjectAcknowledgementRegistrationPersistence projectAcknowledgementRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.ProjectExtentionRegistrationLocalService.class)
	protected com.crowd.funding.database.service.ProjectExtentionRegistrationLocalService projectExtentionRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.ProjectExtentionRegistrationService.class)
	protected com.crowd.funding.database.service.ProjectExtentionRegistrationService projectExtentionRegistrationService;
	@BeanReference(type = ProjectExtentionRegistrationPersistence.class)
	protected ProjectExtentionRegistrationPersistence projectExtentionRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.ProjectFeesRegistrationLocalService.class)
	protected com.crowd.funding.database.service.ProjectFeesRegistrationLocalService projectFeesRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.ProjectFeesRegistrationService.class)
	protected com.crowd.funding.database.service.ProjectFeesRegistrationService projectFeesRegistrationService;
	@BeanReference(type = ProjectFeesRegistrationPersistence.class)
	protected ProjectFeesRegistrationPersistence projectFeesRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.ProjectFollowerRegistrationLocalService.class)
	protected com.crowd.funding.database.service.ProjectFollowerRegistrationLocalService projectFollowerRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.ProjectFollowerRegistrationService.class)
	protected com.crowd.funding.database.service.ProjectFollowerRegistrationService projectFollowerRegistrationService;
	@BeanReference(type = ProjectFollowerRegistrationPersistence.class)
	protected ProjectFollowerRegistrationPersistence projectFollowerRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.ProjectPriorityRegistrationLocalService.class)
	protected com.crowd.funding.database.service.ProjectPriorityRegistrationLocalService projectPriorityRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.ProjectPriorityRegistrationService.class)
	protected com.crowd.funding.database.service.ProjectPriorityRegistrationService projectPriorityRegistrationService;
	@BeanReference(type = ProjectPriorityRegistrationPersistence.class)
	protected ProjectPriorityRegistrationPersistence projectPriorityRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.ProjectRegistrationLocalService.class)
	protected com.crowd.funding.database.service.ProjectRegistrationLocalService projectRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.ProjectRegistrationService.class)
	protected com.crowd.funding.database.service.ProjectRegistrationService projectRegistrationService;
	@BeanReference(type = ProjectRegistrationPersistence.class)
	protected ProjectRegistrationPersistence projectRegistrationPersistence;
	@BeanReference(type = ProjectRegistrationFinder.class)
	protected ProjectRegistrationFinder projectRegistrationFinder;
	@BeanReference(type = com.crowd.funding.database.service.ProjectUpdateRegistrationLocalService.class)
	protected com.crowd.funding.database.service.ProjectUpdateRegistrationLocalService projectUpdateRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.ProjectUpdateRegistrationService.class)
	protected com.crowd.funding.database.service.ProjectUpdateRegistrationService projectUpdateRegistrationService;
	@BeanReference(type = ProjectUpdateRegistrationPersistence.class)
	protected ProjectUpdateRegistrationPersistence projectUpdateRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.QuestionRegistrationLocalService.class)
	protected com.crowd.funding.database.service.QuestionRegistrationLocalService questionRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.QuestionRegistrationService.class)
	protected com.crowd.funding.database.service.QuestionRegistrationService questionRegistrationService;
	@BeanReference(type = QuestionRegistrationPersistence.class)
	protected QuestionRegistrationPersistence questionRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.SubscriptionRegistrationLocalService.class)
	protected com.crowd.funding.database.service.SubscriptionRegistrationLocalService subscriptionRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.SubscriptionRegistrationService.class)
	protected com.crowd.funding.database.service.SubscriptionRegistrationService subscriptionRegistrationService;
	@BeanReference(type = SubscriptionRegistrationPersistence.class)
	protected SubscriptionRegistrationPersistence subscriptionRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.UpdateRequesterRegistrationLocalService.class)
	protected com.crowd.funding.database.service.UpdateRequesterRegistrationLocalService updateRequesterRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.UpdateRequesterRegistrationService.class)
	protected com.crowd.funding.database.service.UpdateRequesterRegistrationService updateRequesterRegistrationService;
	@BeanReference(type = UpdateRequesterRegistrationPersistence.class)
	protected UpdateRequesterRegistrationPersistence updateRequesterRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.UserFollowRegistrationLocalService.class)
	protected com.crowd.funding.database.service.UserFollowRegistrationLocalService userFollowRegistrationLocalService;
	@BeanReference(type = UserFollowRegistrationService.class)
	protected UserFollowRegistrationService userFollowRegistrationService;
	@BeanReference(type = UserFollowRegistrationPersistence.class)
	protected UserFollowRegistrationPersistence userFollowRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.UserOTPRegistrationLocalService.class)
	protected com.crowd.funding.database.service.UserOTPRegistrationLocalService userOTPRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.UserOTPRegistrationService.class)
	protected com.crowd.funding.database.service.UserOTPRegistrationService userOTPRegistrationService;
	@BeanReference(type = UserOTPRegistrationPersistence.class)
	protected UserOTPRegistrationPersistence userOTPRegistrationPersistence;
	@BeanReference(type = com.crowd.funding.database.service.UserRegistrationLocalService.class)
	protected com.crowd.funding.database.service.UserRegistrationLocalService userRegistrationLocalService;
	@BeanReference(type = com.crowd.funding.database.service.UserRegistrationService.class)
	protected com.crowd.funding.database.service.UserRegistrationService userRegistrationService;
	@BeanReference(type = UserRegistrationPersistence.class)
	protected UserRegistrationPersistence userRegistrationPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}