/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

/**
 * The base model interface for the BenificiaryRegistration service. Represents a row in the &quot;cf_project_benificiary_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.BenificiaryRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.BenificiaryRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BenificiaryRegistration
 * @see com.crowd.funding.database.model.impl.BenificiaryRegistrationImpl
 * @see com.crowd.funding.database.model.impl.BenificiaryRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface BenificiaryRegistrationModel extends BaseModel<BenificiaryRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a benificiary registration model instance should use the {@link BenificiaryRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this benificiary registration.
	 *
	 * @return the primary key of this benificiary registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this benificiary registration.
	 *
	 * @param primaryKey the primary key of this benificiary registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this benificiary registration.
	 *
	 * @return the uuid of this benificiary registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this benificiary registration.
	 *
	 * @param uuid the uuid of this benificiary registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the benificiary_id of this benificiary registration.
	 *
	 * @return the benificiary_id of this benificiary registration
	 */
	public long getBENIFICIARY_ID();

	/**
	 * Sets the benificiary_id of this benificiary registration.
	 *
	 * @param BENIFICIARY_ID the benificiary_id of this benificiary registration
	 */
	public void setBENIFICIARY_ID(long BENIFICIARY_ID);

	/**
	 * Returns the benificiary_category of this benificiary registration.
	 *
	 * @return the benificiary_category of this benificiary registration
	 */
	@AutoEscape
	public String getBENIFICIARY_CATEGORY();

	/**
	 * Sets the benificiary_category of this benificiary registration.
	 *
	 * @param BENIFICIARY_CATEGORY the benificiary_category of this benificiary registration
	 */
	public void setBENIFICIARY_CATEGORY(String BENIFICIARY_CATEGORY);

	/**
	 * Returns the benificiary_type of this benificiary registration.
	 *
	 * @return the benificiary_type of this benificiary registration
	 */
	@AutoEscape
	public String getBENIFICIARY_TYPE();

	/**
	 * Sets the benificiary_type of this benificiary registration.
	 *
	 * @param BENIFICIARY_TYPE the benificiary_type of this benificiary registration
	 */
	public void setBENIFICIARY_TYPE(String BENIFICIARY_TYPE);

	/**
	 * Returns the benificiary_name of this benificiary registration.
	 *
	 * @return the benificiary_name of this benificiary registration
	 */
	@AutoEscape
	public String getBENIFICIARY_NAME();

	/**
	 * Sets the benificiary_name of this benificiary registration.
	 *
	 * @param BENIFICIARY_NAME the benificiary_name of this benificiary registration
	 */
	public void setBENIFICIARY_NAME(String BENIFICIARY_NAME);

	/**
	 * Returns the age of this benificiary registration.
	 *
	 * @return the age of this benificiary registration
	 */
	@AutoEscape
	public String getAGE();

	/**
	 * Sets the age of this benificiary registration.
	 *
	 * @param AGE the age of this benificiary registration
	 */
	public void setAGE(String AGE);

	/**
	 * Returns the gender of this benificiary registration.
	 *
	 * @return the gender of this benificiary registration
	 */
	@AutoEscape
	public String getGENDER();

	/**
	 * Sets the gender of this benificiary registration.
	 *
	 * @param GENDER the gender of this benificiary registration
	 */
	public void setGENDER(String GENDER);

	/**
	 * Returns the location of this benificiary registration.
	 *
	 * @return the location of this benificiary registration
	 */
	@AutoEscape
	public String getLOCATION();

	/**
	 * Sets the location of this benificiary registration.
	 *
	 * @param LOCATION the location of this benificiary registration
	 */
	public void setLOCATION(String LOCATION);

	/**
	 * Returns the relationship of this benificiary registration.
	 *
	 * @return the relationship of this benificiary registration
	 */
	@AutoEscape
	public String getRELATIONSHIP();

	/**
	 * Sets the relationship of this benificiary registration.
	 *
	 * @param RELATIONSHIP the relationship of this benificiary registration
	 */
	public void setRELATIONSHIP(String RELATIONSHIP);

	/**
	 * Returns the relationship_details of this benificiary registration.
	 *
	 * @return the relationship_details of this benificiary registration
	 */
	@AutoEscape
	public String getRELATIONSHIP_DETAILS();

	/**
	 * Sets the relationship_details of this benificiary registration.
	 *
	 * @param RELATIONSHIP_DETAILS the relationship_details of this benificiary registration
	 */
	public void setRELATIONSHIP_DETAILS(String RELATIONSHIP_DETAILS);

	/**
	 * Returns the members_no of this benificiary registration.
	 *
	 * @return the members_no of this benificiary registration
	 */
	public int getMEMBERS_NO();

	/**
	 * Sets the members_no of this benificiary registration.
	 *
	 * @param MEMBERS_NO the members_no of this benificiary registration
	 */
	public void setMEMBERS_NO(int MEMBERS_NO);

	/**
	 * Returns the cause_details of this benificiary registration.
	 *
	 * @return the cause_details of this benificiary registration
	 */
	@AutoEscape
	public String getCAUSE_DETAILS();

	/**
	 * Sets the cause_details of this benificiary registration.
	 *
	 * @param CAUSE_DETAILS the cause_details of this benificiary registration
	 */
	public void setCAUSE_DETAILS(String CAUSE_DETAILS);

	/**
	 * Returns the address_line1 of this benificiary registration.
	 *
	 * @return the address_line1 of this benificiary registration
	 */
	@AutoEscape
	public String getADDRESS_LINE1();

	/**
	 * Sets the address_line1 of this benificiary registration.
	 *
	 * @param ADDRESS_LINE1 the address_line1 of this benificiary registration
	 */
	public void setADDRESS_LINE1(String ADDRESS_LINE1);

	/**
	 * Returns the address_line2 of this benificiary registration.
	 *
	 * @return the address_line2 of this benificiary registration
	 */
	@AutoEscape
	public String getADDRESS_LINE2();

	/**
	 * Sets the address_line2 of this benificiary registration.
	 *
	 * @param ADDRESS_LINE2 the address_line2 of this benificiary registration
	 */
	public void setADDRESS_LINE2(String ADDRESS_LINE2);

	/**
	 * Returns the city of this benificiary registration.
	 *
	 * @return the city of this benificiary registration
	 */
	@AutoEscape
	public String getCITY();

	/**
	 * Sets the city of this benificiary registration.
	 *
	 * @param CITY the city of this benificiary registration
	 */
	public void setCITY(String CITY);

	/**
	 * Returns the state of this benificiary registration.
	 *
	 * @return the state of this benificiary registration
	 */
	@AutoEscape
	public String getSTATE();

	/**
	 * Sets the state of this benificiary registration.
	 *
	 * @param STATE the state of this benificiary registration
	 */
	public void setSTATE(String STATE);

	/**
	 * Returns the pincode of this benificiary registration.
	 *
	 * @return the pincode of this benificiary registration
	 */
	public int getPINCODE();

	/**
	 * Sets the pincode of this benificiary registration.
	 *
	 * @param PINCODE the pincode of this benificiary registration
	 */
	public void setPINCODE(int PINCODE);

	/**
	 * Returns the country of this benificiary registration.
	 *
	 * @return the country of this benificiary registration
	 */
	@AutoEscape
	public String getCOUNTRY();

	/**
	 * Sets the country of this benificiary registration.
	 *
	 * @param COUNTRY the country of this benificiary registration
	 */
	public void setCOUNTRY(String COUNTRY);

	/**
	 * Returns the contact_name of this benificiary registration.
	 *
	 * @return the contact_name of this benificiary registration
	 */
	@AutoEscape
	public String getCONTACT_NAME();

	/**
	 * Sets the contact_name of this benificiary registration.
	 *
	 * @param CONTACT_NAME the contact_name of this benificiary registration
	 */
	public void setCONTACT_NAME(String CONTACT_NAME);

	/**
	 * Returns the contact_no of this benificiary registration.
	 *
	 * @return the contact_no of this benificiary registration
	 */
	public long getCONTACT_NO();

	/**
	 * Sets the contact_no of this benificiary registration.
	 *
	 * @param CONTACT_NO the contact_no of this benificiary registration
	 */
	public void setCONTACT_NO(long CONTACT_NO);

	/**
	 * Returns the alternate_contact_no of this benificiary registration.
	 *
	 * @return the alternate_contact_no of this benificiary registration
	 */
	public long getALTERNATE_CONTACT_NO();

	/**
	 * Sets the alternate_contact_no of this benificiary registration.
	 *
	 * @param ALTERNATE_CONTACT_NO the alternate_contact_no of this benificiary registration
	 */
	public void setALTERNATE_CONTACT_NO(long ALTERNATE_CONTACT_NO);

	/**
	 * Returns the emergency_contact_details of this benificiary registration.
	 *
	 * @return the emergency_contact_details of this benificiary registration
	 */
	@AutoEscape
	public String getEMERGENCY_CONTACT_DETAILS();

	/**
	 * Sets the emergency_contact_details of this benificiary registration.
	 *
	 * @param EMERGENCY_CONTACT_DETAILS the emergency_contact_details of this benificiary registration
	 */
	public void setEMERGENCY_CONTACT_DETAILS(String EMERGENCY_CONTACT_DETAILS);

	/**
	 * Returns the image_type of this benificiary registration.
	 *
	 * @return the image_type of this benificiary registration
	 */
	@AutoEscape
	public String getIMAGE_TYPE();

	/**
	 * Sets the image_type of this benificiary registration.
	 *
	 * @param IMAGE_TYPE the image_type of this benificiary registration
	 */
	public void setIMAGE_TYPE(String IMAGE_TYPE);

	/**
	 * Returns the image of this benificiary registration.
	 *
	 * @return the image of this benificiary registration
	 */
	public Blob getIMAGE();

	/**
	 * Sets the image of this benificiary registration.
	 *
	 * @param IMAGE the image of this benificiary registration
	 */
	public void setIMAGE(Blob IMAGE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BenificiaryRegistration benificiaryRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BenificiaryRegistration> toCacheModel();

	@Override
	public BenificiaryRegistration toEscapedModel();

	@Override
	public BenificiaryRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}