/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CategoryRegistration service. Represents a row in the &quot;cf_category_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.CategoryRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.CategoryRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CategoryRegistration
 * @see com.crowd.funding.database.model.impl.CategoryRegistrationImpl
 * @see com.crowd.funding.database.model.impl.CategoryRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface CategoryRegistrationModel extends BaseModel<CategoryRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a category registration model instance should use the {@link CategoryRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this category registration.
	 *
	 * @return the primary key of this category registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this category registration.
	 *
	 * @param primaryKey the primary key of this category registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this category registration.
	 *
	 * @return the uuid of this category registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this category registration.
	 *
	 * @param uuid the uuid of this category registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the category_id of this category registration.
	 *
	 * @return the category_id of this category registration
	 */
	public long getCATEGORY_ID();

	/**
	 * Sets the category_id of this category registration.
	 *
	 * @param CATEGORY_ID the category_id of this category registration
	 */
	public void setCATEGORY_ID(long CATEGORY_ID);

	/**
	 * Returns the category_name of this category registration.
	 *
	 * @return the category_name of this category registration
	 */
	@AutoEscape
	public String getCATEGORY_NAME();

	/**
	 * Sets the category_name of this category registration.
	 *
	 * @param CATEGORY_NAME the category_name of this category registration
	 */
	public void setCATEGORY_NAME(String CATEGORY_NAME);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CategoryRegistration categoryRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CategoryRegistration> toCacheModel();

	@Override
	public CategoryRegistration toEscapedModel();

	@Override
	public CategoryRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}