/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CommentRegistration service. Represents a row in the &quot;cf_project_comment_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.CommentRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.CommentRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommentRegistration
 * @see com.crowd.funding.database.model.impl.CommentRegistrationImpl
 * @see com.crowd.funding.database.model.impl.CommentRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface CommentRegistrationModel extends BaseModel<CommentRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comment registration model instance should use the {@link CommentRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this comment registration.
	 *
	 * @return the primary key of this comment registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this comment registration.
	 *
	 * @param primaryKey the primary key of this comment registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this comment registration.
	 *
	 * @return the uuid of this comment registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this comment registration.
	 *
	 * @param uuid the uuid of this comment registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_comment_id of this comment registration.
	 *
	 * @return the project_comment_id of this comment registration
	 */
	public long getPROJECT_COMMENT_ID();

	/**
	 * Sets the project_comment_id of this comment registration.
	 *
	 * @param PROJECT_COMMENT_ID the project_comment_id of this comment registration
	 */
	public void setPROJECT_COMMENT_ID(long PROJECT_COMMENT_ID);

	/**
	 * Returns the project_id of this comment registration.
	 *
	 * @return the project_id of this comment registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this comment registration.
	 *
	 * @param PROJECT_ID the project_id of this comment registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the comment of this comment registration.
	 *
	 * @return the comment of this comment registration
	 */
	@AutoEscape
	public String getCOMMENT();

	/**
	 * Sets the comment of this comment registration.
	 *
	 * @param COMMENT the comment of this comment registration
	 */
	public void setCOMMENT(String COMMENT);

	/**
	 * Returns the answer of this comment registration.
	 *
	 * @return the answer of this comment registration
	 */
	@AutoEscape
	public String getANSWER();

	/**
	 * Sets the answer of this comment registration.
	 *
	 * @param ANSWER the answer of this comment registration
	 */
	public void setANSWER(String ANSWER);

	/**
	 * Returns the donor_user_id of this comment registration.
	 *
	 * @return the donor_user_id of this comment registration
	 */
	public long getDONOR_USER_ID();

	/**
	 * Sets the donor_user_id of this comment registration.
	 *
	 * @param DONOR_USER_ID the donor_user_id of this comment registration
	 */
	public void setDONOR_USER_ID(long DONOR_USER_ID);

	/**
	 * Returns the comment_date of this comment registration.
	 *
	 * @return the comment_date of this comment registration
	 */
	public Date getCOMMENT_DATE();

	/**
	 * Sets the comment_date of this comment registration.
	 *
	 * @param COMMENT_DATE the comment_date of this comment registration
	 */
	public void setCOMMENT_DATE(Date COMMENT_DATE);

	/**
	 * Returns the status of this comment registration.
	 *
	 * @return the status of this comment registration
	 */
	public int getSTATUS();

	/**
	 * Sets the status of this comment registration.
	 *
	 * @param STATUS the status of this comment registration
	 */
	public void setSTATUS(int STATUS);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CommentRegistration commentRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CommentRegistration> toCacheModel();

	@Override
	public CommentRegistration toEscapedModel();

	@Override
	public CommentRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}