/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HistoryLogRegistration service. Represents a row in the &quot;cf_history_log_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.HistoryLogRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.HistoryLogRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HistoryLogRegistration
 * @see com.crowd.funding.database.model.impl.HistoryLogRegistrationImpl
 * @see com.crowd.funding.database.model.impl.HistoryLogRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface HistoryLogRegistrationModel extends BaseModel<HistoryLogRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a history log registration model instance should use the {@link HistoryLogRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this history log registration.
	 *
	 * @return the primary key of this history log registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this history log registration.
	 *
	 * @param primaryKey the primary key of this history log registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this history log registration.
	 *
	 * @return the uuid of this history log registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this history log registration.
	 *
	 * @param uuid the uuid of this history log registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the history_id of this history log registration.
	 *
	 * @return the history_id of this history log registration
	 */
	public long getHISTORY_ID();

	/**
	 * Sets the history_id of this history log registration.
	 *
	 * @param HISTORY_ID the history_id of this history log registration
	 */
	public void setHISTORY_ID(long HISTORY_ID);

	/**
	 * Returns the user_id of this history log registration.
	 *
	 * @return the user_id of this history log registration
	 */
	public long getUSER_ID();

	/**
	 * Sets the user_id of this history log registration.
	 *
	 * @param USER_ID the user_id of this history log registration
	 */
	public void setUSER_ID(long USER_ID);

	/**
	 * Returns the url of this history log registration.
	 *
	 * @return the url of this history log registration
	 */
	@AutoEscape
	public String getURL();

	/**
	 * Sets the url of this history log registration.
	 *
	 * @param URL the url of this history log registration
	 */
	public void setURL(String URL);

	/**
	 * Returns the date of this history log registration.
	 *
	 * @return the date of this history log registration
	 */
	public Date getDATE();

	/**
	 * Sets the date of this history log registration.
	 *
	 * @param DATE the date of this history log registration
	 */
	public void setDATE(Date DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(HistoryLogRegistration historyLogRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<HistoryLogRegistration> toCacheModel();

	@Override
	public HistoryLogRegistration toEscapedModel();

	@Override
	public HistoryLogRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}