/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PositionRegistration service. Represents a row in the &quot;cf_position_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.PositionRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.PositionRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PositionRegistration
 * @see com.crowd.funding.database.model.impl.PositionRegistrationImpl
 * @see com.crowd.funding.database.model.impl.PositionRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface PositionRegistrationModel extends BaseModel<PositionRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a position registration model instance should use the {@link PositionRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this position registration.
	 *
	 * @return the primary key of this position registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this position registration.
	 *
	 * @param primaryKey the primary key of this position registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this position registration.
	 *
	 * @return the uuid of this position registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this position registration.
	 *
	 * @param uuid the uuid of this position registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the position_id of this position registration.
	 *
	 * @return the position_id of this position registration
	 */
	public long getPOSITION_ID();

	/**
	 * Sets the position_id of this position registration.
	 *
	 * @param POSITION_ID the position_id of this position registration
	 */
	public void setPOSITION_ID(long POSITION_ID);

	/**
	 * Returns the advertisment_num of this position registration.
	 *
	 * @return the advertisment_num of this position registration
	 */
	@AutoEscape
	public String getADVERTISMENT_NUM();

	/**
	 * Sets the advertisment_num of this position registration.
	 *
	 * @param ADVERTISMENT_NUM the advertisment_num of this position registration
	 */
	public void setADVERTISMENT_NUM(String ADVERTISMENT_NUM);

	/**
	 * Returns the position_name of this position registration.
	 *
	 * @return the position_name of this position registration
	 */
	@AutoEscape
	public String getPOSITION_NAME();

	/**
	 * Sets the position_name of this position registration.
	 *
	 * @param POSITION_NAME the position_name of this position registration
	 */
	public void setPOSITION_NAME(String POSITION_NAME);

	/**
	 * Returns the description of this position registration.
	 *
	 * @return the description of this position registration
	 */
	@AutoEscape
	public String getDESCRIPTION();

	/**
	 * Sets the description of this position registration.
	 *
	 * @param DESCRIPTION the description of this position registration
	 */
	public void setDESCRIPTION(String DESCRIPTION);

	/**
	 * Returns the experience_level of this position registration.
	 *
	 * @return the experience_level of this position registration
	 */
	@AutoEscape
	public String getEXPERIENCE_LEVEL();

	/**
	 * Sets the experience_level of this position registration.
	 *
	 * @param EXPERIENCE_LEVEL the experience_level of this position registration
	 */
	public void setEXPERIENCE_LEVEL(String EXPERIENCE_LEVEL);

	/**
	 * Returns the salary of this position registration.
	 *
	 * @return the salary of this position registration
	 */
	@AutoEscape
	public String getSALARY();

	/**
	 * Sets the salary of this position registration.
	 *
	 * @param SALARY the salary of this position registration
	 */
	public void setSALARY(String SALARY);

	/**
	 * Returns the industry_type of this position registration.
	 *
	 * @return the industry_type of this position registration
	 */
	@AutoEscape
	public String getINDUSTRY_TYPE();

	/**
	 * Sets the industry_type of this position registration.
	 *
	 * @param INDUSTRY_TYPE the industry_type of this position registration
	 */
	public void setINDUSTRY_TYPE(String INDUSTRY_TYPE);

	/**
	 * Returns the functional_area of this position registration.
	 *
	 * @return the functional_area of this position registration
	 */
	@AutoEscape
	public String getFUNCTIONAL_AREA();

	/**
	 * Sets the functional_area of this position registration.
	 *
	 * @param FUNCTIONAL_AREA the functional_area of this position registration
	 */
	public void setFUNCTIONAL_AREA(String FUNCTIONAL_AREA);

	/**
	 * Returns the role_category of this position registration.
	 *
	 * @return the role_category of this position registration
	 */
	@AutoEscape
	public String getROLE_CATEGORY();

	/**
	 * Sets the role_category of this position registration.
	 *
	 * @param ROLE_CATEGORY the role_category of this position registration
	 */
	public void setROLE_CATEGORY(String ROLE_CATEGORY);

	/**
	 * Returns the employment_type of this position registration.
	 *
	 * @return the employment_type of this position registration
	 */
	@AutoEscape
	public String getEMPLOYMENT_TYPE();

	/**
	 * Sets the employment_type of this position registration.
	 *
	 * @param EMPLOYMENT_TYPE the employment_type of this position registration
	 */
	public void setEMPLOYMENT_TYPE(String EMPLOYMENT_TYPE);

	/**
	 * Returns the location of this position registration.
	 *
	 * @return the location of this position registration
	 */
	@AutoEscape
	public String getLOCATION();

	/**
	 * Sets the location of this position registration.
	 *
	 * @param LOCATION the location of this position registration
	 */
	public void setLOCATION(String LOCATION);

	/**
	 * Returns the date of this position registration.
	 *
	 * @return the date of this position registration
	 */
	public Date getDATE();

	/**
	 * Sets the date of this position registration.
	 *
	 * @param DATE the date of this position registration
	 */
	public void setDATE(Date DATE);

	/**
	 * Returns the status of this position registration.
	 *
	 * @return the status of this position registration
	 */
	public int getSTATUS();

	/**
	 * Sets the status of this position registration.
	 *
	 * @param STATUS the status of this position registration
	 */
	public void setSTATUS(int STATUS);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PositionRegistration positionRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PositionRegistration> toCacheModel();

	@Override
	public PositionRegistration toEscapedModel();

	@Override
	public PositionRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}