/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProjectUpdateRegistration service. Represents a row in the &quot;cf_project_update_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.ProjectUpdateRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.ProjectUpdateRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectUpdateRegistration
 * @see com.crowd.funding.database.model.impl.ProjectUpdateRegistrationImpl
 * @see com.crowd.funding.database.model.impl.ProjectUpdateRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface ProjectUpdateRegistrationModel extends BaseModel<ProjectUpdateRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project update registration model instance should use the {@link ProjectUpdateRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this project update registration.
	 *
	 * @return the primary key of this project update registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project update registration.
	 *
	 * @param primaryKey the primary key of this project update registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project update registration.
	 *
	 * @return the uuid of this project update registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this project update registration.
	 *
	 * @param uuid the uuid of this project update registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_update_id of this project update registration.
	 *
	 * @return the project_update_id of this project update registration
	 */
	public long getPROJECT_UPDATE_ID();

	/**
	 * Sets the project_update_id of this project update registration.
	 *
	 * @param PROJECT_UPDATE_ID the project_update_id of this project update registration
	 */
	public void setPROJECT_UPDATE_ID(long PROJECT_UPDATE_ID);

	/**
	 * Returns the project_id of this project update registration.
	 *
	 * @return the project_id of this project update registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this project update registration.
	 *
	 * @param PROJECT_ID the project_id of this project update registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the update_details of this project update registration.
	 *
	 * @return the update_details of this project update registration
	 */
	@AutoEscape
	public String getUPDATE_DETAILS();

	/**
	 * Sets the update_details of this project update registration.
	 *
	 * @param UPDATE_DETAILS the update_details of this project update registration
	 */
	public void setUPDATE_DETAILS(String UPDATE_DETAILS);

	/**
	 * Returns the update_date of this project update registration.
	 *
	 * @return the update_date of this project update registration
	 */
	public Date getUPDATE_DATE();

	/**
	 * Sets the update_date of this project update registration.
	 *
	 * @param UPDATE_DATE the update_date of this project update registration
	 */
	public void setUPDATE_DATE(Date UPDATE_DATE);

	/**
	 * Returns the status of this project update registration.
	 *
	 * @return the status of this project update registration
	 */
	public int getSTATUS();

	/**
	 * Sets the status of this project update registration.
	 *
	 * @param STATUS the status of this project update registration
	 */
	public void setSTATUS(int STATUS);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProjectUpdateRegistration projectUpdateRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectUpdateRegistration> toCacheModel();

	@Override
	public ProjectUpdateRegistration toEscapedModel();

	@Override
	public ProjectUpdateRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}