/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the ProjectAcknowledgementRegistration service. Represents a row in the &quot;cf_acknowledgement_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.ProjectAcknowledgementRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.ProjectAcknowledgementRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectAcknowledgementRegistration
 * @see com.crowd.funding.database.model.impl.ProjectAcknowledgementRegistrationImpl
 * @see com.crowd.funding.database.model.impl.ProjectAcknowledgementRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface ProjectAcknowledgementRegistrationModel extends BaseModel<ProjectAcknowledgementRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project acknowledgement registration model instance should use the {@link ProjectAcknowledgementRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this project acknowledgement registration.
	 *
	 * @return the primary key of this project acknowledgement registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project acknowledgement registration.
	 *
	 * @param primaryKey the primary key of this project acknowledgement registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project acknowledgement registration.
	 *
	 * @return the uuid of this project acknowledgement registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this project acknowledgement registration.
	 *
	 * @param uuid the uuid of this project acknowledgement registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the acknowledgment_id of this project acknowledgement registration.
	 *
	 * @return the acknowledgment_id of this project acknowledgement registration
	 */
	public long getACKNOWLEDGMENT_ID();

	/**
	 * Sets the acknowledgment_id of this project acknowledgement registration.
	 *
	 * @param ACKNOWLEDGMENT_ID the acknowledgment_id of this project acknowledgement registration
	 */
	public void setACKNOWLEDGMENT_ID(long ACKNOWLEDGMENT_ID);

	/**
	 * Returns the project_id of this project acknowledgement registration.
	 *
	 * @return the project_id of this project acknowledgement registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this project acknowledgement registration.
	 *
	 * @param PROJECT_ID the project_id of this project acknowledgement registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the details of this project acknowledgement registration.
	 *
	 * @return the details of this project acknowledgement registration
	 */
	@AutoEscape
	public String getDETAILS();

	/**
	 * Sets the details of this project acknowledgement registration.
	 *
	 * @param DETAILS the details of this project acknowledgement registration
	 */
	public void setDETAILS(String DETAILS);

	/**
	 * Returns the document_name of this project acknowledgement registration.
	 *
	 * @return the document_name of this project acknowledgement registration
	 */
	@AutoEscape
	public String getDOCUMENT_NAME();

	/**
	 * Sets the document_name of this project acknowledgement registration.
	 *
	 * @param DOCUMENT_NAME the document_name of this project acknowledgement registration
	 */
	public void setDOCUMENT_NAME(String DOCUMENT_NAME);

	/**
	 * Returns the document_type of this project acknowledgement registration.
	 *
	 * @return the document_type of this project acknowledgement registration
	 */
	@AutoEscape
	public String getDOCUMENT_TYPE();

	/**
	 * Sets the document_type of this project acknowledgement registration.
	 *
	 * @param DOCUMENT_TYPE the document_type of this project acknowledgement registration
	 */
	public void setDOCUMENT_TYPE(String DOCUMENT_TYPE);

	/**
	 * Returns the document of this project acknowledgement registration.
	 *
	 * @return the document of this project acknowledgement registration
	 */
	public Blob getDOCUMENT();

	/**
	 * Sets the document of this project acknowledgement registration.
	 *
	 * @param DOCUMENT the document of this project acknowledgement registration
	 */
	public void setDOCUMENT(Blob DOCUMENT);

	/**
	 * Returns the video_type of this project acknowledgement registration.
	 *
	 * @return the video_type of this project acknowledgement registration
	 */
	@AutoEscape
	public String getVIDEO_TYPE();

	/**
	 * Sets the video_type of this project acknowledgement registration.
	 *
	 * @param VIDEO_TYPE the video_type of this project acknowledgement registration
	 */
	public void setVIDEO_TYPE(String VIDEO_TYPE);

	/**
	 * Returns the video of this project acknowledgement registration.
	 *
	 * @return the video of this project acknowledgement registration
	 */
	public Blob getVIDEO();

	/**
	 * Sets the video of this project acknowledgement registration.
	 *
	 * @param VIDEO the video of this project acknowledgement registration
	 */
	public void setVIDEO(Blob VIDEO);

	/**
	 * Returns the date of this project acknowledgement registration.
	 *
	 * @return the date of this project acknowledgement registration
	 */
	public Date getDATE();

	/**
	 * Sets the date of this project acknowledgement registration.
	 *
	 * @param DATE the date of this project acknowledgement registration
	 */
	public void setDATE(Date DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ProjectAcknowledgementRegistration projectAcknowledgementRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectAcknowledgementRegistration> toCacheModel();

	@Override
	public ProjectAcknowledgementRegistration toEscapedModel();

	@Override
	public ProjectAcknowledgementRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}