/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProjectFeesRegistration service. Represents a row in the &quot;cf_project_fees_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.ProjectFeesRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.ProjectFeesRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectFeesRegistration
 * @see com.crowd.funding.database.model.impl.ProjectFeesRegistrationImpl
 * @see com.crowd.funding.database.model.impl.ProjectFeesRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface ProjectFeesRegistrationModel extends BaseModel<ProjectFeesRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project fees registration model instance should use the {@link ProjectFeesRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this project fees registration.
	 *
	 * @return the primary key of this project fees registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project fees registration.
	 *
	 * @param primaryKey the primary key of this project fees registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project fees registration.
	 *
	 * @return the uuid of this project fees registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this project fees registration.
	 *
	 * @param uuid the uuid of this project fees registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_fees_id of this project fees registration.
	 *
	 * @return the project_fees_id of this project fees registration
	 */
	public long getPROJECT_FEES_ID();

	/**
	 * Sets the project_fees_id of this project fees registration.
	 *
	 * @param PROJECT_FEES_ID the project_fees_id of this project fees registration
	 */
	public void setPROJECT_FEES_ID(long PROJECT_FEES_ID);

	/**
	 * Returns the category_id of this project fees registration.
	 *
	 * @return the category_id of this project fees registration
	 */
	public long getCATEGORY_ID();

	/**
	 * Sets the category_id of this project fees registration.
	 *
	 * @param CATEGORY_ID the category_id of this project fees registration
	 */
	public void setCATEGORY_ID(long CATEGORY_ID);

	/**
	 * Returns the project_id of this project fees registration.
	 *
	 * @return the project_id of this project fees registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this project fees registration.
	 *
	 * @param PROJECT_ID the project_id of this project fees registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the start_amount of this project fees registration.
	 *
	 * @return the start_amount of this project fees registration
	 */
	public float getSTART_AMOUNT();

	/**
	 * Sets the start_amount of this project fees registration.
	 *
	 * @param START_AMOUNT the start_amount of this project fees registration
	 */
	public void setSTART_AMOUNT(float START_AMOUNT);

	/**
	 * Returns the end_amount of this project fees registration.
	 *
	 * @return the end_amount of this project fees registration
	 */
	public float getEND_AMOUNT();

	/**
	 * Sets the end_amount of this project fees registration.
	 *
	 * @param END_AMOUNT the end_amount of this project fees registration
	 */
	public void setEND_AMOUNT(float END_AMOUNT);

	/**
	 * Returns the withdraw_status of this project fees registration.
	 *
	 * @return the withdraw_status of this project fees registration
	 */
	public int getWITHDRAW_STATUS();

	/**
	 * Sets the withdraw_status of this project fees registration.
	 *
	 * @param WITHDRAW_STATUS the withdraw_status of this project fees registration
	 */
	public void setWITHDRAW_STATUS(int WITHDRAW_STATUS);

	/**
	 * Returns the date of this project fees registration.
	 *
	 * @return the date of this project fees registration
	 */
	public Date getDATE();

	/**
	 * Sets the date of this project fees registration.
	 *
	 * @param DATE the date of this project fees registration
	 */
	public void setDATE(Date DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProjectFeesRegistration projectFeesRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectFeesRegistration> toCacheModel();

	@Override
	public ProjectFeesRegistration toEscapedModel();

	@Override
	public ProjectFeesRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}