/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the ProjectRegistration service. Represents a row in the &quot;cf_project_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.ProjectRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.ProjectRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectRegistration
 * @see com.crowd.funding.database.model.impl.ProjectRegistrationImpl
 * @see com.crowd.funding.database.model.impl.ProjectRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface ProjectRegistrationModel extends BaseModel<ProjectRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project registration model instance should use the {@link ProjectRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this project registration.
	 *
	 * @return the primary key of this project registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project registration.
	 *
	 * @param primaryKey the primary key of this project registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project registration.
	 *
	 * @return the uuid of this project registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this project registration.
	 *
	 * @param uuid the uuid of this project registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_id of this project registration.
	 *
	 * @return the project_id of this project registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this project registration.
	 *
	 * @param PROJECT_ID the project_id of this project registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the user_id of this project registration.
	 *
	 * @return the user_id of this project registration
	 */
	public long getUSER_ID();

	/**
	 * Sets the user_id of this project registration.
	 *
	 * @param USER_ID the user_id of this project registration
	 */
	public void setUSER_ID(long USER_ID);

	/**
	 * Returns the benificiary_id of this project registration.
	 *
	 * @return the benificiary_id of this project registration
	 */
	public long getBENIFICIARY_ID();

	/**
	 * Sets the benificiary_id of this project registration.
	 *
	 * @param BENIFICIARY_ID the benificiary_id of this project registration
	 */
	public void setBENIFICIARY_ID(long BENIFICIARY_ID);

	/**
	 * Returns the title of this project registration.
	 *
	 * @return the title of this project registration
	 */
	@AutoEscape
	public String getTITLE();

	/**
	 * Sets the title of this project registration.
	 *
	 * @param TITLE the title of this project registration
	 */
	public void setTITLE(String TITLE);

	/**
	 * Returns the description of this project registration.
	 *
	 * @return the description of this project registration
	 */
	@AutoEscape
	public String getDESCRIPTION();

	/**
	 * Sets the description of this project registration.
	 *
	 * @param DESCRIPTION the description of this project registration
	 */
	public void setDESCRIPTION(String DESCRIPTION);

	/**
	 * Returns the video_type of this project registration.
	 *
	 * @return the video_type of this project registration
	 */
	@AutoEscape
	public String getVIDEO_TYPE();

	/**
	 * Sets the video_type of this project registration.
	 *
	 * @param VIDEO_TYPE the video_type of this project registration
	 */
	public void setVIDEO_TYPE(String VIDEO_TYPE);

	/**
	 * Returns the video of this project registration.
	 *
	 * @return the video of this project registration
	 */
	public Blob getVIDEO();

	/**
	 * Sets the video of this project registration.
	 *
	 * @param VIDEO the video of this project registration
	 */
	public void setVIDEO(Blob VIDEO);

	/**
	 * Returns the required_fund_amount of this project registration.
	 *
	 * @return the required_fund_amount of this project registration
	 */
	public float getREQUIRED_FUND_AMOUNT();

	/**
	 * Sets the required_fund_amount of this project registration.
	 *
	 * @param REQUIRED_FUND_AMOUNT the required_fund_amount of this project registration
	 */
	public void setREQUIRED_FUND_AMOUNT(float REQUIRED_FUND_AMOUNT);

	/**
	 * Returns the creation_date of this project registration.
	 *
	 * @return the creation_date of this project registration
	 */
	public Date getCREATION_DATE();

	/**
	 * Sets the creation_date of this project registration.
	 *
	 * @param CREATION_DATE the creation_date of this project registration
	 */
	public void setCREATION_DATE(Date CREATION_DATE);

	/**
	 * Returns the end_date of this project registration.
	 *
	 * @return the end_date of this project registration
	 */
	public Date getEND_DATE();

	/**
	 * Sets the end_date of this project registration.
	 *
	 * @param END_DATE the end_date of this project registration
	 */
	public void setEND_DATE(Date END_DATE);

	/**
	 * Returns the comment of this project registration.
	 *
	 * @return the comment of this project registration
	 */
	@AutoEscape
	public String getCOMMENT();

	/**
	 * Sets the comment of this project registration.
	 *
	 * @param COMMENT the comment of this project registration
	 */
	public void setCOMMENT(String COMMENT);

	/**
	 * Returns the status of this project registration.
	 *
	 * @return the status of this project registration
	 */
	public int getSTATUS();

	/**
	 * Sets the status of this project registration.
	 *
	 * @param STATUS the status of this project registration
	 */
	public void setSTATUS(int STATUS);

	/**
	 * Returns the request_status of this project registration.
	 *
	 * @return the request_status of this project registration
	 */
	public int getREQUEST_STATUS();

	/**
	 * Sets the request_status of this project registration.
	 *
	 * @param REQUEST_STATUS the request_status of this project registration
	 */
	public void setREQUEST_STATUS(int REQUEST_STATUS);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProjectRegistration projectRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectRegistration> toCacheModel();

	@Override
	public ProjectRegistration toEscapedModel();

	@Override
	public ProjectRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}