/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProjectExtentionRegistration service. Represents a row in the &quot;cf_extention_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.ProjectExtentionRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.ProjectExtentionRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectExtentionRegistration
 * @see com.crowd.funding.database.model.impl.ProjectExtentionRegistrationImpl
 * @see com.crowd.funding.database.model.impl.ProjectExtentionRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface ProjectExtentionRegistrationModel extends BaseModel<ProjectExtentionRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project extention registration model instance should use the {@link ProjectExtentionRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this project extention registration.
	 *
	 * @return the primary key of this project extention registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project extention registration.
	 *
	 * @param primaryKey the primary key of this project extention registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project extention registration.
	 *
	 * @return the uuid of this project extention registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this project extention registration.
	 *
	 * @param uuid the uuid of this project extention registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_extention_id of this project extention registration.
	 *
	 * @return the project_extention_id of this project extention registration
	 */
	public long getPROJECT_EXTENTION_ID();

	/**
	 * Sets the project_extention_id of this project extention registration.
	 *
	 * @param PROJECT_EXTENTION_ID the project_extention_id of this project extention registration
	 */
	public void setPROJECT_EXTENTION_ID(long PROJECT_EXTENTION_ID);

	/**
	 * Returns the project_id of this project extention registration.
	 *
	 * @return the project_id of this project extention registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this project extention registration.
	 *
	 * @param PROJECT_ID the project_id of this project extention registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the extention_date of this project extention registration.
	 *
	 * @return the extention_date of this project extention registration
	 */
	public Date getEXTENTION_DATE();

	/**
	 * Sets the extention_date of this project extention registration.
	 *
	 * @param EXTENTION_DATE the extention_date of this project extention registration
	 */
	public void setEXTENTION_DATE(Date EXTENTION_DATE);

	/**
	 * Returns the comment of this project extention registration.
	 *
	 * @return the comment of this project extention registration
	 */
	@AutoEscape
	public String getCOMMENT();

	/**
	 * Sets the comment of this project extention registration.
	 *
	 * @param COMMENT the comment of this project extention registration
	 */
	public void setCOMMENT(String COMMENT);

	/**
	 * Returns the status of this project extention registration.
	 *
	 * @return the status of this project extention registration
	 */
	public int getSTATUS();

	/**
	 * Sets the status of this project extention registration.
	 *
	 * @param STATUS the status of this project extention registration
	 */
	public void setSTATUS(int STATUS);

	/**
	 * Returns the date of this project extention registration.
	 *
	 * @return the date of this project extention registration
	 */
	public Date getDATE();

	/**
	 * Sets the date of this project extention registration.
	 *
	 * @param DATE the date of this project extention registration
	 */
	public void setDATE(Date DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ProjectExtentionRegistration projectExtentionRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectExtentionRegistration> toCacheModel();

	@Override
	public ProjectExtentionRegistration toEscapedModel();

	@Override
	public ProjectExtentionRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}