/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QuestionRegistration service. Represents a row in the &quot;cf_project_question_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.QuestionRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.QuestionRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuestionRegistration
 * @see com.crowd.funding.database.model.impl.QuestionRegistrationImpl
 * @see com.crowd.funding.database.model.impl.QuestionRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface QuestionRegistrationModel extends BaseModel<QuestionRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question registration model instance should use the {@link QuestionRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this question registration.
	 *
	 * @return the primary key of this question registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this question registration.
	 *
	 * @param primaryKey the primary key of this question registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this question registration.
	 *
	 * @return the uuid of this question registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this question registration.
	 *
	 * @param uuid the uuid of this question registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project_question_id of this question registration.
	 *
	 * @return the project_question_id of this question registration
	 */
	public long getPROJECT_QUESTION_ID();

	/**
	 * Sets the project_question_id of this question registration.
	 *
	 * @param PROJECT_QUESTION_ID the project_question_id of this question registration
	 */
	public void setPROJECT_QUESTION_ID(long PROJECT_QUESTION_ID);

	/**
	 * Returns the project_id of this question registration.
	 *
	 * @return the project_id of this question registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this question registration.
	 *
	 * @param PROJECT_ID the project_id of this question registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the question of this question registration.
	 *
	 * @return the question of this question registration
	 */
	@AutoEscape
	public String getQUESTION();

	/**
	 * Sets the question of this question registration.
	 *
	 * @param QUESTION the question of this question registration
	 */
	public void setQUESTION(String QUESTION);

	/**
	 * Returns the question_requester_user_id of this question registration.
	 *
	 * @return the question_requester_user_id of this question registration
	 */
	public long getQUESTION_REQUESTER_USER_ID();

	/**
	 * Sets the question_requester_user_id of this question registration.
	 *
	 * @param QUESTION_REQUESTER_USER_ID the question_requester_user_id of this question registration
	 */
	public void setQUESTION_REQUESTER_USER_ID(long QUESTION_REQUESTER_USER_ID);

	/**
	 * Returns the question_date of this question registration.
	 *
	 * @return the question_date of this question registration
	 */
	public Date getQUESTION_DATE();

	/**
	 * Sets the question_date of this question registration.
	 *
	 * @param QUESTION_DATE the question_date of this question registration
	 */
	public void setQUESTION_DATE(Date QUESTION_DATE);

	/**
	 * Returns the status of this question registration.
	 *
	 * @return the status of this question registration
	 */
	public int getSTATUS();

	/**
	 * Sets the status of this question registration.
	 *
	 * @param STATUS the status of this question registration
	 */
	public void setSTATUS(int STATUS);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QuestionRegistration questionRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QuestionRegistration> toCacheModel();

	@Override
	public QuestionRegistration toEscapedModel();

	@Override
	public QuestionRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}