/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.crowd.funding.database.model.FeedbackRegistration;
import com.crowd.funding.database.model.FeedbackRegistrationModel;
import com.crowd.funding.database.model.FeedbackRegistrationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FeedbackRegistration service. Represents a row in the &quot;cf_project_feedback_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link FeedbackRegistrationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FeedbackRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FeedbackRegistrationImpl
 * @see FeedbackRegistration
 * @see FeedbackRegistrationModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class FeedbackRegistrationModelImpl extends BaseModelImpl<FeedbackRegistration>
	implements FeedbackRegistrationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a feedback registration model instance should use the {@link FeedbackRegistration} interface instead.
	 */
	public static final String TABLE_NAME = "cf_project_feedback_details";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "PROJECT_FEEDBACK_ID", Types.BIGINT },
			{ "PROJECT_ID", Types.BIGINT },
			{ "FEEDBACK", Types.VARCHAR },
			{ "DONOR_USER_ID", Types.BIGINT },
			{ "FEEDBACK_DATE", Types.TIMESTAMP },
			{ "STATUS", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PROJECT_FEEDBACK_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("PROJECT_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FEEDBACK", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DONOR_USER_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FEEDBACK_DATE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("STATUS", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table cf_project_feedback_details (uuid_ VARCHAR(75) null,PROJECT_FEEDBACK_ID LONG not null primary key,PROJECT_ID LONG,FEEDBACK TEXT null,DONOR_USER_ID LONG,FEEDBACK_DATE DATE null,STATUS INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table cf_project_feedback_details";
	public static final String ORDER_BY_JPQL = " ORDER BY feedbackRegistration.PROJECT_FEEDBACK_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY cf_project_feedback_details.PROJECT_FEEDBACK_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.crowd.funding.database.model.FeedbackRegistration"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.crowd.funding.database.model.FeedbackRegistration"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.crowd.funding.database.model.FeedbackRegistration"),
			true);
	public static final long PROJECT_FEEDBACK_ID_COLUMN_BITMASK = 1L;
	public static final long PROJECT_ID_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FeedbackRegistration toModel(
		FeedbackRegistrationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FeedbackRegistration model = new FeedbackRegistrationImpl();

		model.setUuid(soapModel.getUuid());
		model.setPROJECT_FEEDBACK_ID(soapModel.getPROJECT_FEEDBACK_ID());
		model.setPROJECT_ID(soapModel.getPROJECT_ID());
		model.setFEEDBACK(soapModel.getFEEDBACK());
		model.setDONOR_USER_ID(soapModel.getDONOR_USER_ID());
		model.setFEEDBACK_DATE(soapModel.getFEEDBACK_DATE());
		model.setSTATUS(soapModel.getSTATUS());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FeedbackRegistration> toModels(
		FeedbackRegistrationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FeedbackRegistration> models = new ArrayList<FeedbackRegistration>(soapModels.length);

		for (FeedbackRegistrationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.crowd.funding.database.service.util.ServiceProps.get(
				"lock.expiration.time.com.crowd.funding.database.model.FeedbackRegistration"));

	public FeedbackRegistrationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PROJECT_FEEDBACK_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPROJECT_FEEDBACK_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PROJECT_FEEDBACK_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FeedbackRegistration.class;
	}

	@Override
	public String getModelClassName() {
		return FeedbackRegistration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("PROJECT_FEEDBACK_ID", getPROJECT_FEEDBACK_ID());
		attributes.put("PROJECT_ID", getPROJECT_ID());
		attributes.put("FEEDBACK", getFEEDBACK());
		attributes.put("DONOR_USER_ID", getDONOR_USER_ID());
		attributes.put("FEEDBACK_DATE", getFEEDBACK_DATE());
		attributes.put("STATUS", getSTATUS());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long PROJECT_FEEDBACK_ID = (Long)attributes.get("PROJECT_FEEDBACK_ID");

		if (PROJECT_FEEDBACK_ID != null) {
			setPROJECT_FEEDBACK_ID(PROJECT_FEEDBACK_ID);
		}

		Long PROJECT_ID = (Long)attributes.get("PROJECT_ID");

		if (PROJECT_ID != null) {
			setPROJECT_ID(PROJECT_ID);
		}

		String FEEDBACK = (String)attributes.get("FEEDBACK");

		if (FEEDBACK != null) {
			setFEEDBACK(FEEDBACK);
		}

		Long DONOR_USER_ID = (Long)attributes.get("DONOR_USER_ID");

		if (DONOR_USER_ID != null) {
			setDONOR_USER_ID(DONOR_USER_ID);
		}

		Date FEEDBACK_DATE = (Date)attributes.get("FEEDBACK_DATE");

		if (FEEDBACK_DATE != null) {
			setFEEDBACK_DATE(FEEDBACK_DATE);
		}

		Integer STATUS = (Integer)attributes.get("STATUS");

		if (STATUS != null) {
			setSTATUS(STATUS);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPROJECT_FEEDBACK_ID() {
		return _PROJECT_FEEDBACK_ID;
	}

	@Override
	public void setPROJECT_FEEDBACK_ID(long PROJECT_FEEDBACK_ID) {
		_columnBitmask |= PROJECT_FEEDBACK_ID_COLUMN_BITMASK;

		if (!_setOriginalPROJECT_FEEDBACK_ID) {
			_setOriginalPROJECT_FEEDBACK_ID = true;

			_originalPROJECT_FEEDBACK_ID = _PROJECT_FEEDBACK_ID;
		}

		_PROJECT_FEEDBACK_ID = PROJECT_FEEDBACK_ID;
	}

	public long getOriginalPROJECT_FEEDBACK_ID() {
		return _originalPROJECT_FEEDBACK_ID;
	}

	@JSON
	@Override
	public long getPROJECT_ID() {
		return _PROJECT_ID;
	}

	@Override
	public void setPROJECT_ID(long PROJECT_ID) {
		_columnBitmask |= PROJECT_ID_COLUMN_BITMASK;

		if (!_setOriginalPROJECT_ID) {
			_setOriginalPROJECT_ID = true;

			_originalPROJECT_ID = _PROJECT_ID;
		}

		_PROJECT_ID = PROJECT_ID;
	}

	public long getOriginalPROJECT_ID() {
		return _originalPROJECT_ID;
	}

	@JSON
	@Override
	public String getFEEDBACK() {
		if (_FEEDBACK == null) {
			return "";
		}
		else {
			return _FEEDBACK;
		}
	}

	@Override
	public void setFEEDBACK(String FEEDBACK) {
		_FEEDBACK = FEEDBACK;
	}

	@JSON
	@Override
	public long getDONOR_USER_ID() {
		return _DONOR_USER_ID;
	}

	@Override
	public void setDONOR_USER_ID(long DONOR_USER_ID) {
		_DONOR_USER_ID = DONOR_USER_ID;
	}

	@JSON
	@Override
	public Date getFEEDBACK_DATE() {
		return _FEEDBACK_DATE;
	}

	@Override
	public void setFEEDBACK_DATE(Date FEEDBACK_DATE) {
		_FEEDBACK_DATE = FEEDBACK_DATE;
	}

	@JSON
	@Override
	public int getSTATUS() {
		return _STATUS;
	}

	@Override
	public void setSTATUS(int STATUS) {
		_STATUS = STATUS;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FeedbackRegistration.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FeedbackRegistration toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FeedbackRegistration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FeedbackRegistrationImpl feedbackRegistrationImpl = new FeedbackRegistrationImpl();

		feedbackRegistrationImpl.setUuid(getUuid());
		feedbackRegistrationImpl.setPROJECT_FEEDBACK_ID(getPROJECT_FEEDBACK_ID());
		feedbackRegistrationImpl.setPROJECT_ID(getPROJECT_ID());
		feedbackRegistrationImpl.setFEEDBACK(getFEEDBACK());
		feedbackRegistrationImpl.setDONOR_USER_ID(getDONOR_USER_ID());
		feedbackRegistrationImpl.setFEEDBACK_DATE(getFEEDBACK_DATE());
		feedbackRegistrationImpl.setSTATUS(getSTATUS());

		feedbackRegistrationImpl.resetOriginalValues();

		return feedbackRegistrationImpl;
	}

	@Override
	public int compareTo(FeedbackRegistration feedbackRegistration) {
		long primaryKey = feedbackRegistration.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FeedbackRegistration)) {
			return false;
		}

		FeedbackRegistration feedbackRegistration = (FeedbackRegistration)obj;

		long primaryKey = feedbackRegistration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		FeedbackRegistrationModelImpl feedbackRegistrationModelImpl = this;

		feedbackRegistrationModelImpl._originalUuid = feedbackRegistrationModelImpl._uuid;

		feedbackRegistrationModelImpl._originalPROJECT_FEEDBACK_ID = feedbackRegistrationModelImpl._PROJECT_FEEDBACK_ID;

		feedbackRegistrationModelImpl._setOriginalPROJECT_FEEDBACK_ID = false;

		feedbackRegistrationModelImpl._originalPROJECT_ID = feedbackRegistrationModelImpl._PROJECT_ID;

		feedbackRegistrationModelImpl._setOriginalPROJECT_ID = false;

		feedbackRegistrationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FeedbackRegistration> toCacheModel() {
		FeedbackRegistrationCacheModel feedbackRegistrationCacheModel = new FeedbackRegistrationCacheModel();

		feedbackRegistrationCacheModel.uuid = getUuid();

		String uuid = feedbackRegistrationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			feedbackRegistrationCacheModel.uuid = null;
		}

		feedbackRegistrationCacheModel.PROJECT_FEEDBACK_ID = getPROJECT_FEEDBACK_ID();

		feedbackRegistrationCacheModel.PROJECT_ID = getPROJECT_ID();

		feedbackRegistrationCacheModel.FEEDBACK = getFEEDBACK();

		String FEEDBACK = feedbackRegistrationCacheModel.FEEDBACK;

		if ((FEEDBACK != null) && (FEEDBACK.length() == 0)) {
			feedbackRegistrationCacheModel.FEEDBACK = null;
		}

		feedbackRegistrationCacheModel.DONOR_USER_ID = getDONOR_USER_ID();

		Date FEEDBACK_DATE = getFEEDBACK_DATE();

		if (FEEDBACK_DATE != null) {
			feedbackRegistrationCacheModel.FEEDBACK_DATE = FEEDBACK_DATE.getTime();
		}
		else {
			feedbackRegistrationCacheModel.FEEDBACK_DATE = Long.MIN_VALUE;
		}

		feedbackRegistrationCacheModel.STATUS = getSTATUS();

		return feedbackRegistrationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", PROJECT_FEEDBACK_ID=");
		sb.append(getPROJECT_FEEDBACK_ID());
		sb.append(", PROJECT_ID=");
		sb.append(getPROJECT_ID());
		sb.append(", FEEDBACK=");
		sb.append(getFEEDBACK());
		sb.append(", DONOR_USER_ID=");
		sb.append(getDONOR_USER_ID());
		sb.append(", FEEDBACK_DATE=");
		sb.append(getFEEDBACK_DATE());
		sb.append(", STATUS=");
		sb.append(getSTATUS());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.crowd.funding.database.model.FeedbackRegistration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PROJECT_FEEDBACK_ID</column-name><column-value><![CDATA[");
		sb.append(getPROJECT_FEEDBACK_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PROJECT_ID</column-name><column-value><![CDATA[");
		sb.append(getPROJECT_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FEEDBACK</column-name><column-value><![CDATA[");
		sb.append(getFEEDBACK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DONOR_USER_ID</column-name><column-value><![CDATA[");
		sb.append(getDONOR_USER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FEEDBACK_DATE</column-name><column-value><![CDATA[");
		sb.append(getFEEDBACK_DATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>STATUS</column-name><column-value><![CDATA[");
		sb.append(getSTATUS());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = FeedbackRegistration.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			FeedbackRegistration.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _PROJECT_FEEDBACK_ID;
	private long _originalPROJECT_FEEDBACK_ID;
	private boolean _setOriginalPROJECT_FEEDBACK_ID;
	private long _PROJECT_ID;
	private long _originalPROJECT_ID;
	private boolean _setOriginalPROJECT_ID;
	private String _FEEDBACK;
	private long _DONOR_USER_ID;
	private Date _FEEDBACK_DATE;
	private int _STATUS;
	private long _columnBitmask;
	private FeedbackRegistration _escapedModel;
}