/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.crowd.funding.database.model.ProjectFollowerRegistration;
import com.crowd.funding.database.model.ProjectFollowerRegistrationModel;
import com.crowd.funding.database.model.ProjectFollowerRegistrationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ProjectFollowerRegistration service. Represents a row in the &quot;cf_project_follower_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ProjectFollowerRegistrationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectFollowerRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectFollowerRegistrationImpl
 * @see ProjectFollowerRegistration
 * @see ProjectFollowerRegistrationModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ProjectFollowerRegistrationModelImpl extends BaseModelImpl<ProjectFollowerRegistration>
	implements ProjectFollowerRegistrationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project follower registration model instance should use the {@link ProjectFollowerRegistration} interface instead.
	 */
	public static final String TABLE_NAME = "cf_project_follower_details";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "PROJECT_FOLLOWER_ID", Types.BIGINT },
			{ "USER_ID", Types.BIGINT },
			{ "PROJECT_ID", Types.BIGINT },
			{ "STATUS", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PROJECT_FOLLOWER_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("USER_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("PROJECT_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("STATUS", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table cf_project_follower_details (uuid_ VARCHAR(75) null,PROJECT_FOLLOWER_ID LONG not null primary key,USER_ID LONG,PROJECT_ID LONG,STATUS INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table cf_project_follower_details";
	public static final String ORDER_BY_JPQL = " ORDER BY projectFollowerRegistration.PROJECT_FOLLOWER_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY cf_project_follower_details.PROJECT_FOLLOWER_ID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.crowd.funding.database.model.ProjectFollowerRegistration"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.crowd.funding.database.model.ProjectFollowerRegistration"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.crowd.funding.database.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.crowd.funding.database.model.ProjectFollowerRegistration"),
			true);
	public static final long PROJECT_FOLLOWER_ID_COLUMN_BITMASK = 1L;
	public static final long PROJECT_ID_COLUMN_BITMASK = 2L;
	public static final long USER_ID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ProjectFollowerRegistration toModel(
		ProjectFollowerRegistrationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ProjectFollowerRegistration model = new ProjectFollowerRegistrationImpl();

		model.setUuid(soapModel.getUuid());
		model.setPROJECT_FOLLOWER_ID(soapModel.getPROJECT_FOLLOWER_ID());
		model.setUSER_ID(soapModel.getUSER_ID());
		model.setPROJECT_ID(soapModel.getPROJECT_ID());
		model.setSTATUS(soapModel.getSTATUS());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ProjectFollowerRegistration> toModels(
		ProjectFollowerRegistrationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ProjectFollowerRegistration> models = new ArrayList<ProjectFollowerRegistration>(soapModels.length);

		for (ProjectFollowerRegistrationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.crowd.funding.database.service.util.ServiceProps.get(
				"lock.expiration.time.com.crowd.funding.database.model.ProjectFollowerRegistration"));

	public ProjectFollowerRegistrationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PROJECT_FOLLOWER_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPROJECT_FOLLOWER_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PROJECT_FOLLOWER_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProjectFollowerRegistration.class;
	}

	@Override
	public String getModelClassName() {
		return ProjectFollowerRegistration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("PROJECT_FOLLOWER_ID", getPROJECT_FOLLOWER_ID());
		attributes.put("USER_ID", getUSER_ID());
		attributes.put("PROJECT_ID", getPROJECT_ID());
		attributes.put("STATUS", getSTATUS());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long PROJECT_FOLLOWER_ID = (Long)attributes.get("PROJECT_FOLLOWER_ID");

		if (PROJECT_FOLLOWER_ID != null) {
			setPROJECT_FOLLOWER_ID(PROJECT_FOLLOWER_ID);
		}

		Long USER_ID = (Long)attributes.get("USER_ID");

		if (USER_ID != null) {
			setUSER_ID(USER_ID);
		}

		Long PROJECT_ID = (Long)attributes.get("PROJECT_ID");

		if (PROJECT_ID != null) {
			setPROJECT_ID(PROJECT_ID);
		}

		Integer STATUS = (Integer)attributes.get("STATUS");

		if (STATUS != null) {
			setSTATUS(STATUS);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPROJECT_FOLLOWER_ID() {
		return _PROJECT_FOLLOWER_ID;
	}

	@Override
	public void setPROJECT_FOLLOWER_ID(long PROJECT_FOLLOWER_ID) {
		_columnBitmask |= PROJECT_FOLLOWER_ID_COLUMN_BITMASK;

		if (!_setOriginalPROJECT_FOLLOWER_ID) {
			_setOriginalPROJECT_FOLLOWER_ID = true;

			_originalPROJECT_FOLLOWER_ID = _PROJECT_FOLLOWER_ID;
		}

		_PROJECT_FOLLOWER_ID = PROJECT_FOLLOWER_ID;
	}

	public long getOriginalPROJECT_FOLLOWER_ID() {
		return _originalPROJECT_FOLLOWER_ID;
	}

	@JSON
	@Override
	public long getUSER_ID() {
		return _USER_ID;
	}

	@Override
	public void setUSER_ID(long USER_ID) {
		_columnBitmask |= USER_ID_COLUMN_BITMASK;

		if (!_setOriginalUSER_ID) {
			_setOriginalUSER_ID = true;

			_originalUSER_ID = _USER_ID;
		}

		_USER_ID = USER_ID;
	}

	public long getOriginalUSER_ID() {
		return _originalUSER_ID;
	}

	@JSON
	@Override
	public long getPROJECT_ID() {
		return _PROJECT_ID;
	}

	@Override
	public void setPROJECT_ID(long PROJECT_ID) {
		_columnBitmask |= PROJECT_ID_COLUMN_BITMASK;

		if (!_setOriginalPROJECT_ID) {
			_setOriginalPROJECT_ID = true;

			_originalPROJECT_ID = _PROJECT_ID;
		}

		_PROJECT_ID = PROJECT_ID;
	}

	public long getOriginalPROJECT_ID() {
		return _originalPROJECT_ID;
	}

	@JSON
	@Override
	public int getSTATUS() {
		return _STATUS;
	}

	@Override
	public void setSTATUS(int STATUS) {
		_STATUS = STATUS;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ProjectFollowerRegistration.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProjectFollowerRegistration toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ProjectFollowerRegistration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectFollowerRegistrationImpl projectFollowerRegistrationImpl = new ProjectFollowerRegistrationImpl();

		projectFollowerRegistrationImpl.setUuid(getUuid());
		projectFollowerRegistrationImpl.setPROJECT_FOLLOWER_ID(getPROJECT_FOLLOWER_ID());
		projectFollowerRegistrationImpl.setUSER_ID(getUSER_ID());
		projectFollowerRegistrationImpl.setPROJECT_ID(getPROJECT_ID());
		projectFollowerRegistrationImpl.setSTATUS(getSTATUS());

		projectFollowerRegistrationImpl.resetOriginalValues();

		return projectFollowerRegistrationImpl;
	}

	@Override
	public int compareTo(
		ProjectFollowerRegistration projectFollowerRegistration) {
		long primaryKey = projectFollowerRegistration.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ProjectFollowerRegistration)) {
			return false;
		}

		ProjectFollowerRegistration projectFollowerRegistration = (ProjectFollowerRegistration)obj;

		long primaryKey = projectFollowerRegistration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ProjectFollowerRegistrationModelImpl projectFollowerRegistrationModelImpl =
			this;

		projectFollowerRegistrationModelImpl._originalUuid = projectFollowerRegistrationModelImpl._uuid;

		projectFollowerRegistrationModelImpl._originalPROJECT_FOLLOWER_ID = projectFollowerRegistrationModelImpl._PROJECT_FOLLOWER_ID;

		projectFollowerRegistrationModelImpl._setOriginalPROJECT_FOLLOWER_ID = false;

		projectFollowerRegistrationModelImpl._originalUSER_ID = projectFollowerRegistrationModelImpl._USER_ID;

		projectFollowerRegistrationModelImpl._setOriginalUSER_ID = false;

		projectFollowerRegistrationModelImpl._originalPROJECT_ID = projectFollowerRegistrationModelImpl._PROJECT_ID;

		projectFollowerRegistrationModelImpl._setOriginalPROJECT_ID = false;

		projectFollowerRegistrationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ProjectFollowerRegistration> toCacheModel() {
		ProjectFollowerRegistrationCacheModel projectFollowerRegistrationCacheModel =
			new ProjectFollowerRegistrationCacheModel();

		projectFollowerRegistrationCacheModel.uuid = getUuid();

		String uuid = projectFollowerRegistrationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			projectFollowerRegistrationCacheModel.uuid = null;
		}

		projectFollowerRegistrationCacheModel.PROJECT_FOLLOWER_ID = getPROJECT_FOLLOWER_ID();

		projectFollowerRegistrationCacheModel.USER_ID = getUSER_ID();

		projectFollowerRegistrationCacheModel.PROJECT_ID = getPROJECT_ID();

		projectFollowerRegistrationCacheModel.STATUS = getSTATUS();

		return projectFollowerRegistrationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", PROJECT_FOLLOWER_ID=");
		sb.append(getPROJECT_FOLLOWER_ID());
		sb.append(", USER_ID=");
		sb.append(getUSER_ID());
		sb.append(", PROJECT_ID=");
		sb.append(getPROJECT_ID());
		sb.append(", STATUS=");
		sb.append(getSTATUS());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append(
			"com.crowd.funding.database.model.ProjectFollowerRegistration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PROJECT_FOLLOWER_ID</column-name><column-value><![CDATA[");
		sb.append(getPROJECT_FOLLOWER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>USER_ID</column-name><column-value><![CDATA[");
		sb.append(getUSER_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PROJECT_ID</column-name><column-value><![CDATA[");
		sb.append(getPROJECT_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>STATUS</column-name><column-value><![CDATA[");
		sb.append(getSTATUS());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ProjectFollowerRegistration.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ProjectFollowerRegistration.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _PROJECT_FOLLOWER_ID;
	private long _originalPROJECT_FOLLOWER_ID;
	private boolean _setOriginalPROJECT_FOLLOWER_ID;
	private long _USER_ID;
	private long _originalUSER_ID;
	private boolean _setOriginalUSER_ID;
	private long _PROJECT_ID;
	private long _originalPROJECT_ID;
	private boolean _setOriginalPROJECT_ID;
	private int _STATUS;
	private long _columnBitmask;
	private ProjectFollowerRegistration _escapedModel;
}